### PR TITLE
fix(dropdown, menu): made menu text work in dark theme

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3411

### CODE REVIEW

**Comment by srambach** [comment]
👍 LGTM! Thank you!

**Review by mattnolting — APPROVED** [review]
LPTM 👍

**Review by srambach — APPROVED** [review]

**Review by mattnolting — APPROVED** [review]
LGTM 👍

**Review by christiemolloy — APPROVED** [review]
perfecttt

**Pull request merged**
