### PR TITLE
feat(workspace): use new doc theme

### PR DESCRIPTION
**Pull request by redallen**
Port of [`theme-patternfly-org`](https://www.npmjs.com/package/theme-patternfly-org) to core. Replaces Gatsby with custom `unified` and `webpack` based build system. New doc features like tabs and [example captions]() are now supported.

Changes:
- Move some content around per patternfly.org design
  - Fix syntax issues with contributon.md
    - Change `{` to `&lbrace;`
    - Remove out-of-date gulp consumer guide
    - Add `noLive` to HTML code blocks
  - Replace index.md with index.js
- Add new start, serve, and screenshot scripts
  - Update clean task
- Add new full screen example thumbnails
- Remove gatsby and its dependencies
- Remove dev:lite in favor of webpack-based build which is now just as fast to reload SASS, HBS, or MD file changes and its dependencies
  - Builds in CI ~1m10s faster ([new@3m4s](https://app.circleci.com/pipelines/github/patternfly/patternfly/1642/workflows/3255e99f-6029-451d-b4e5-8a3f54efc7c9/jobs/4147) / [old@4m12s](https://app.circleci.com/pipelines/github/patternfly/patternfly/1642/workflows/3255e99f-6029-451d-b4e5-8a3f54efc7c9/jobs/4147))
- Remove unused scripts
- Upgrade CI to node 12
- Temporarily remove `test:a11y` since theme does not list fullscreen pages in a JSON file anymore. New `test:a11y` script is coming this month from @jschuler and @jessiehuff with improved coverage and reporting.

### CODE REVIEW

**Review by mcoker — APPROVED** [review]
LOVE IT! Thanks @redallen!!

**Review by mattnolting — APPROVED** [review]
❤️  it. 🚢  it!

**Review by christiemolloy — APPROVED** [review]
LGTM!!!!

**Pull request merged**
