### PR TITLE
fix(button): fixed primary toggle state styles

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4631

### CODE REVIEW

**Comment by mcarrano** [comment]
What does this change exactly @mcoker ?  Issue references Split Button but PR references Primary toggle.

**Comment by mmenestr** [comment]
@mcarrano i think it's fixing the primary toggle button haha and if I'm looking at the right thing (ie: no light blue underline when you hover, but instead the whole button is the same uniform color) then it looks good to me @mcoker !

**Review by mmenestr — APPROVED** [review]

**Comment by mcoker** [comment]
> What does this change exactly @mcoker ? Issue references Split Button but PR references Primary toggle.

@mcarrano the primary split button is getting a blue bottom border on focus/active when it shouldn't. Also the main (non-split) primary toggle hover states are broken. This PR fixes those 2 things.

**Review by mcarrano — APPROVED** [review]
Thanks for the explanation @mcoker @mmenestr . I'm good then!

**Review by srambach — APPROVED** [review]
LGTM

**Pull request merged**
