### PR TITLE
fix(simple-list): remove bold on focus, active, selected/current

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4085

This PR removes the bold text. Do we want to make any other changes?

### CODE REVIEW

**Review by gdoyle1 — APPROVED** [review]
@mcoker This fixes our use case in OpenShift, so good with me! 

I know @lboehling also mentioned maybe not including the text color change in hover state but not sure what the final consensus was on it - I'm good with either

**Review by mcarrano — APPROVED** [review]
Looks good to me. Thanks @mcoker !

**Comment by mcoker** [comment]
@gdoyle1 removed the text color change on hover/focus, too

**Review by mattnolting — APPROVED** [review]
LPTM 🌮

**Review by mceledonia — APPROVED** [review]

**Comment by gdoyle1** [comment]
nice! LGTM

**Review by gdoyle1 — APPROVED** [review]

**Pull request merged**
