### PR TITLE
chore(demos): updated page header user dropdown to use plain toggle

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4069

### CODE REVIEW

**Comment by mmenestr** [comment]
I'm still seeing a white outline? This problem also occurs in the table demos btw

**Comment by mcoker** [comment]
@mmenestr did you go into the demo or are you looking at the screenshot preview of the demo?

The screenshots still show the outline on https://patternfly-pr-4070.surge.sh/components/page/html-demos but if you go into the demos, the outline should be gone

* https://patternfly-pr-4070.surge.sh/components/page/html-demos/sticky-tertiary-nav/
* https://patternfly-pr-4070.surge.sh/components/table/html-demos/basic/

**Comment by mmenestr** [comment]
@mcoker Oh my bad, you're right, I was looking at the 'previews' only. Looks good to me!

**Comment by mcoker** [comment]
@mmenestr cool! Those screenshots have to be manually updated and we typically do that as part of the release process with each release, so they'll be updated on patternfly.org when the changes from this PR are live in the next release.

**Review by mattnolting — APPROVED** [review]
LPTM 🚀

**Pull request merged**
