### PR TITLE
fix(treeview): selectable/expandable node bugs

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4990

### CODE REVIEW

**Comment by mmenestr** [comment]
This looks good if it's just making the expanded nodes black, and the collapsed nodes grey?

**Review by mmenestr — APPROVED** [review]

**Comment by mcoker** [comment]
@mmenestr yep, the only other visual change is

> If you apply `.pf-m-current` to a selectable node and hover the toggle, it turns blue. It should turn black instead.

You can see that works in this example - https://patternfly-pr-4991.surge.sh/components/tree-view#with-selectable-expandable-nodes

You can see the bug it fixes in this example in @kmcfaul's PR - https://patternfly-react-pr-7714.surge.sh/components/tree-view#with-separate-selection-and-expansion
* Select an expandable row by clicking on the text, then hover over the toggle button and note the arrow turns blue instead of black.

**Comment by mcoker** [comment]
Updated the expandable/selectable non-checkbox node to be a `div` with a `button` toggle element inside per @kmcfaul's feedback. Also worked on the aria-labels a bit. It should read "select [node text]" now for the non-checkbox expandable/selectable node and checkbox treeview's checkbox inputs. And it updates the selectable/expandable and checkbox toggles' labels to read "toggle [node text]"

**Review by thatblindgeye — COMMENTED** [review]
Looks good! I am noticing an issue when navigating via VO in the checkbox example.

The items that only have a checkbox (no expandable toggle) seem to have inaccurate labeling. In Application 1, Settings gets announced as "Select loader settings, level 3", for example. The same applies for Application 1 > Loader, and Application 2 > Settings (the second one).

The checkbox's `aria-labelledby` are pulling in the `text-` ID from the selectable/expandable example rather than their own example.

**Comment by mcoker** [comment]
@thatblindgeye ah hah! Sorry for the delay, I was trying to wrap my head around some non-repetitive logic to set a flag to enable the text `id` when appropriate and ended up using our `concat` helper to basically serve as an `or` operator. Hopefully that works!

**Review by thatblindgeye — APPROVED** [review]
🎉 Looks good! I created https://github.com/patternfly/patternfly/issues/5010 as a followup to the issue we discussed

**Pull request merged**
