### PR TITLE
fix(charts): fixed dark theme chart var prefix

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/5672

### CODE REVIEW

**Review by evwilkin — APPROVED** [review]
LGTM

**Comment by srambach** [comment]
It looks like PF4 uses `pf-c-chart` so why wouldn't we want `pf-v5-c-chart`?

**Comment by mcoker** [comment]
@srambach where are you seeing `pf-c-chart`? This is what I'm seeing on the `v4` branch:

* CSS vars - https://github.com/patternfly/patternfly/blob/v4/src/patternfly/patternfly-charts.scss
* SCSS vars - https://github.com/patternfly/patternfly/blob/v4/src/patternfly/base/_chart-globals.scss
* dark SCSS vars - https://github.com/patternfly/patternfly/blob/v4/src/patternfly/base/themes/dark/_chart-globals.scss

**Review by srambach — APPROVED** [review]
Let's leave it matching how it was in PF4 - looks good.

**Pull request merged**
