### PR TITLE
feat(card-demo): added demos for horizontal cards

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3555
fixes https://github.com/patternfly/patternfly/issues/1635

Along with adding the card demos, I needed to update 2 things:

* Added a plain list variant. This removes the bullet and left padding of a list. The demo shows a top level plain list with a nested regular list. That was filed in a separate issue - https://github.com/patternfly/patternfly/issues/1635
* Fixed a bug where - if the card title is a child of pf-c-card__header, we remove all padding. There was a bug where if the title was the first-child in __header, it was assigned a padding-top, and if it was not the last child, it got a padding-bottom.

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
I think this looks good @mcoker . The only thing that feels a bit off is the way the action/link wraps in the footer. Is that because the footer is aligned to the bottom of the container?

@gdoyle1 can you also take a look to see if this is in line with what you expected?

**Comment by mcoker** [comment]
@mcarrano yep, this is what it looks like in the full page demo

Screen Shot 2020-12-16 at 12 56 15 PM

And here is the design

Screen Shot 2020-12-16 at 12 58 44 PM

**Comment by gdoyle1** [comment]
Looks amazing!!! @mcoker So excited for this, thank you!

**Comment by mcoker** [comment]
@mcarrano @gdoyle1 @mceledonia added a horizontal split demo, too - https://patternfly-pr-3758.surge.sh/components/card/html-demos/#horizontal-split

**Comment by gdoyle1** [comment]
> @mcarrano @gdoyle1 @mceledonia added a horizontal split demo, too - https://patternfly-pr-3758.surge.sh/components/card/html-demos/#horizontal-split

Going to add @ajacobs21e to review that split card too!

**Comment by mcoker** [comment]
Also @mceledonia @mcarrano @mattnolting @christiemolloy  as part of this PR...

* Added a [plain list variant](https://patternfly-pr-3758.surge.sh/components/list#plain). This removes the bullet and left padding of a list. The demo shows a top level plain list with a nested regular list.
* Fixed a bug where - if the card title is a child of `pf-c-card__header`, we remove all padding. There was a bug where if the title was the first-child in `__header`, it was assigned a padding-top, and if it was not the last child, it got a padding-bottom.

**Comment by mcarrano** [comment]
I think this all looks great @mcoker . And also thanks for adding the plain list variant. I had that lined up for a future spring so that's one I can cross off from the list!

**Comment by ajacobs21e** [comment]
oo it's perfect @mcoker !

**Review by mattnolting — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
