### PR TITLE
feat(clipboard-copy): added inline variant

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3906

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
This looks great @mcoker .

**Comment by christianvogt** [comment]
If you put two code block immediately adjacent they end up looking like this. Can you tell what is being copied by each?

image

**Comment by lwrigh** [comment]
> If you put two code block immediately adjacent they end up looking like this. Can you tell what is being copied by each?
> 
> image
> 
> Do we need a border? a hover state? a less then line-height background?

I think adding a white border or adding a bit of white space at the beginning and end of the inline code snippet would do the trick if there's one right after the other.

**Comment by mcoker** [comment]
Hey @christianvogt! If you made that change in the PR, the space won't show up because our workspace removes the whitespace between inline elements, so as long as an application doesn't remove that whitespace, the a space character will exist between two inline clipboard copy elements like this. In our examples, you would need to add a `&nbsp;` between them so that the whitespace isn't removed.

Screen Shot 2021-03-17 at 12 15 00 PM

**Comment by christianvogt** [comment]
@mcoker yes I forgot to add explicit spacing between the two blocks. But do we still need to separate the line backgrounds vertically?

image

Also, when using `<code>`. Should the outer `div` changed to `code`? or should the inner `span` (`<code class="pf-c-clipboard-copy__text"`) be changed?

**Comment by mcoker** [comment]
> Also, when using <code>. Should the outer div changed to code? or should the inner span (<code class="pf-c-clipboard-copy__text") be changed?

We could use `<code>` although a user could put anything they want in there, so it's not always going to be code. If we did support that as the default element or as a `component` variant to specify the element used to wrap the text, we would need additional styling to override the monospace font the browser automatically adds when using `<code>`. @jessiehuff WDYT?

**Comment by christianvogt** [comment]
I'm not saying to have it as the default. But I want to be able to use the `code` element as part of this component. This will need to be supported in the react-component. We will want the monospaced for our use case.

My question was more directly to the implementation and whether we should replace the outer `div` or the inner `span` when we want to use the `code` element.

**Comment by mcoker** [comment]
> I want to be able to use the code element as part of this component. This will need to be supported in the react-component. We will want the monospaced for our use case.

@mcarrano @lwrigh is that a variation we should support in core? In order to get the PF monospaced font stack with a `<code>` block, we will need to add support for that in the clipboard copy component.

> whether we should replace the outer div or the inner span when we want to use the code element.

@christianvogt the inner `span.pf-c-clipboard-copy__text` element since you wouldn't want to include the copy button or any additional actions.

**Comment by mcarrano** [comment]
@mcoker I think it makes sense to allow using a `<code>` block inside this component. Is that something that can be doe as part of this PR?

**Comment by mcoker** [comment]
@christianvogt @lwrigh @mcarrano added the code variant here - https://patternfly-pr-3933.surge.sh/components/clipboard-copy#inline

**Comment by lwrigh** [comment]
That's looking good to me! My only comment is is there any way to include an automatic space after the code snippet ends in the long string that wraps and the in sentence one?

**Comment by mcarrano** [comment]
Looks good to me, too.

**Comment by mcoker** [comment]
>  is is there any way to include an automatic space after the code snippet ends in the long string that wraps and the in sentence one?

@lwrigh yep, we made a workspace change that removed it so I updated the example to add it back. Let me know if it looks OK now.

**Comment by lwrigh** [comment]
That looks good to me!

**Review by mattnolting — APPROVED** [review]
LPTM!

**Comment by christianvogt** [comment]
@mcoker @lwrigh i just wanted to point out that i've had some inquiries about how the background of inline code blocks touch the line above making it harder to distinguish separate blocks. This can be seen in the screenshots posted in this PR.
Is there a chance we can address this or are we set on the final design?

**Comment by mcoker** [comment]
@christianvogt @lwrigh sorry for the delay on this, there is a PR up with the change - https://github.com/patternfly/patternfly/pull/4296 if you'd like to leave your feedback.

**Pull request merged**
