### PR TITLE
feat(button): added progress support with plain variation

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4561

### CODE REVIEW

**Review by mmenestr — APPROVED** [review]
This LGTM!

**Review by mcarrano — APPROVED** [review]
Looks good to me!

**Review by mattnolting — APPROVED** [review]
LPTM!

**Review by jgiardino — APPROVED** [review]
Agree with the "LPTM"! Thank you so much

**Pull request merged**
