### PR TITLE
feat(font): update usage of redhatfont

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/5114

--

* Updates font files to the latest from https://github.com/RedHatOfficial/RedHatFont/tree/master/webfonts
* Removes
  1. `.pf-m-redhat-updated-font` - opt-in no longer needed
  1. `.pf-m-redhatmono-font` - opt-in to RedHatMono, no longer needed as it's the default mono font now
  1. `--pf-global--FontWeight--light` - this is not used anywhere
* Changes
  1. `--pf-global--FontFamily--sans-serif` to `--pf-global--FontFamily--text`
  1. `--pf-global--FontFamily--heading--sans-serif` to `--pf-global--FontFamily--heading`
  1. `--pf-global--FontFamily--redhatVF--(.*)` to `--pf-global--FontFamily--$1--vf`
  1. `.pf-m-redhatVF-font` to `.pf-m-vf-font` - opt-in class for variable font

### CODE REVIEW

**Comment by mcoker** [comment]
@srambach @mattnolting @mceledonia @mcarrano this is ready for review. There is an issue with the way some workspace titles are displaying since there are hard-coded styles for workspace-specific titles. For example, the "examples", "documentation", and "overview" titles here are all using the wrong font-family because the variables for font family names were simplified. That should be easily fixed via org, which we're already working on to support the dark theme switcher. The component examples themselves should all have the right font styling.

**Review by srambach — APPROVED** [review]
Looks great 👍

**Comment by mcoker** [comment]
@srambach @mattnolting would you mind giving this another look after rebasing? Also updated the stylelint rule for sass `$pf-` pattern linting to include "v5"

**Review by mattnolting — APPROVED** [review]
LPTM 👍

**Pull request merged**
