### PR TITLE
fix(brand+card): update examples to display in dark theme

### PR DESCRIPTION
**Pull request by jenny-s51**
Towards #5613

### CODE REVIEW

**Review by mcoker — COMMENTED** [review]
Thanks @jenny-s51! My initial thought is that I'm not sure if we want to go down the road of introducing an enhancement to individual components to support toggling between the base and dark themes. Initially I was thinking we would add local workspace styles to the examples to toggle any images we want to swap between themes, by targeting the image or whatever it is using the dark theme class selector. But I'm curious what others think. @srambach @mattnolting 

```
.some-image--dark, // hide dark image by default
.pf-v5-theme-dark .some-image { // hide light image when dark theme is set
  display: none;
}

.pf-v5-theme-dark .some-image--dark { // show dark image when dark theme is set
  display: revert;
}
```

**Comment by jenny-s51** [comment]
Thank you @mcoker for your feedback on this - it sounds like we want to take a different approach here. Just want to confirm... does [this change](https://github.com/patternfly/patternfly/issues/5801) need to go in before we can make any subsequent updates to this PR?

**Comment by mcoker** [comment]
@jenny-s51 I don't think so, we could just update the examples that use brand to use the local style method described in https://github.com/patternfly/patternfly/pull/5681#pullrequestreview-1522981635 and we can follow up with the brand enhancement later and yank out the local styles.

**Review by jenny-s51 — COMMENTED** [review]
@mattnolting @mcoker thanks again for all your great feedback on this! The dark/light switching behavior now seems to be working as expected. If this PR looks good to you guys, we may be able to just merge this in and close https://github.com/patternfly/patternfly/issues/5613 since the original issue has been addressed. 

Were there any other changes you either of you wanted to see added to this PR?

**Pull request merged**
