### PR TITLE
feat(icons): added open-drawer-right pficon

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/5147

icons page - https://patternfly-pr-5160.surge.sh/icons

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good to me! @lboehling can you also take a look?

**Comment by evwilkin** [comment]
FYI once this is merged & the updated Core release pulled into PF-React, we should be unblocked for https://github.com/patternfly/patternfly-org/issues/3223 to add this icon to the website.

**Review by lboehling — APPROVED** [review]
perfect! thank you!

**Review by evwilkin — APPROVED** [review]
LGTM

**Pull request merged**
