### PR TITLE
fix(skeleton): improved animation performance

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3965

### CODE REVIEW

**Comment by mcoker** [comment]
@mattnolting wdyt about this one?

**Comment by srambach** [comment]
I see it up in the gpu now, looks good to me.

**Comment by mcoker** [comment]
@srambach thanks! Would you mind approving and merging the PR?

**Review by mattnolting — APPROVED** [review]
LPTM

**Pull request merged**
