### PR TITLE
feat(expandable-section): added indented variation

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4566

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
This looks good @mcoker . I can definitely see how this is useful. Is this something that requires React follow up (assume yes)? And if so could you open an issue? 

I can try to get this into the January milestone but we are already pretty overloaded. @jgiardino do you have any specific scheduling requirements?

**Comment by mcoker** [comment]
@mcarrano here's the react issue - https://github.com/patternfly/patternfly-react/issues/6705

I can do the react work once this PR is merged

**Comment by jgiardino** [comment]
These updates look great! Thanks for adding this so quickly.

@mcarrano We are hoping to move do usability testing as soon as we're able to get a couple more updates in place. I don't know yet how many sprints are needed to add that. One is adding expandable sections, which would be simple, but our other task might be a little more complicated. So 2 or 3 sprints is my best guess. 

I'm not opposed to using the class name that provides this until it's supported in the react component, but I can follow up with our UI dev team to see if this is not an option.

**Comment by srambach** [comment]
LGTM, and much needed imho :-)

**Review by srambach — APPROVED** [review]

**Pull request merged**
