### PR TITLE
chore(page): updated example content, made text readable

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4920

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
Looks good to me. Does everything pass a11y requirements @mcoker ?

**Comment by mcoker** [comment]
@mcarrano yep, though when I ran it through axe, it reported a different contrast issue with white text against our `.pf-m-dark-200` page section

Screen Shot 2022-10-25 at 11 11 48 AM

Updated that as a local workspace fix to adjust the text color against that background.

Screen Shot 2022-10-25 at 11 10 38 AM

**Review by srambach — APPROVED** [review]
LGTM 👍

**Review by mattnolting — APPROVED** [review]
👍

**Pull request merged**
