### PR TITLE
fix(card): fix clickable label positioning

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/6352

### CODE REVIEW

**Review by srambach — APPROVED** [review]
Quick sleuthing! You're a supergenius 🦸

**Comment by mattnolting** [comment]
This example isn't responding to the update. 

https://github.com/patternfly/patternfly/assets/5385435/b2b6c9d9-a140-4bbb-a385-e98ea3360fe2

Screenshot 2024-02-27 at 11 14 54 PM

Screenshot 2024-02-27 at 11 15 30 PM

**Comment by mattnolting** [comment]
> @mattnolting _I believe_ the clickable/selectable card works differently - the card title triggers the "clickable" feature and the input triggers the "selectable". If you look at org on firefox or safari, the react examples show how it should behave - https://www.patternfly.org/components/card/#clickable-and-selectable. And the html example in FF matches what's in this PR - https://www.patternfly.org/components/card/html#clickable-and-selectable

Nice, thanks for expanding on that!

**Review by mattnolting — APPROVED** [review]
👁️👁️ LPTM!

**Pull request merged**
