### PR TITLE
chore(copy-clipboard): renamed inline examples to inline compact

### PR DESCRIPTION
**Pull request by mcoker**
Renaming the examples per https://github.com/patternfly/patternfly-react/pull/5629#discussion_r611918535

### CODE REVIEW

**Review by mattnolting — APPROVED** [review]
LGTM! 🚢

**Comment by mcoker** [comment]
@mcarrano updated the example names per https://github.com/patternfly/patternfly-react/pull/5629#issuecomment-819740458

https://patternfly-pr-3998.surge.sh/components/clipboard-copy#inline-compact

**Review by mcarrano — APPROVED** [review]
Looks great. Thanks @mcoker !

**Pull request merged**
