### PR TITLE
fix(input-group): added z-index

### LINKED ISSUE #3926: Input group focus rings are truncated
Input groups join widgets right next to each other. In the default state, that's fine. However, when one of the widgets in the group gets focus, the ring is chopped off for everything but the last child.

Screenshots from https://www.patternfly.org/v4/components/input-group (with focus):

Screenshot from 2021-03-15 13-13-14

Screenshot from 2021-03-15 13-12-53

Screenshot from 2021-03-15 13-12-58

Screenshot from 2021-03-15 13-13-01

### PR DESCRIPTION
**Pull request by mattnolting**
closes #3926 

Added `z-index` to `:focus`

### CODE REVIEW

**Comment by garrett** [comment]
This isn't fixed here. I just tested the preview page for input groups @ https://patternfly-pr-3991.surge.sh/components/input-group and got the following:

Screenshot from 2021-04-12 16-11-11
Screenshot from 2021-04-12 16-11-08
Screenshot from 2021-04-12 16-11-04
Screenshot from 2021-04-12 16-11-01
Screenshot from 2021-04-12 16-10-51
... additional groups are also affected, but the above demonstrates it enough.

Note the truncation of the focus ring on one or both sides, depending on the group's neighboring widgets.

**Review by garrett — CHANGES_REQUESTED** [review]
Thanks for the effort, but this isn't fixed.

I just tested the preview page for input groups @ https://patternfly-pr-3991.surge.sh/components/input-group and got the following:

Screenshot from 2021-04-12 16-11-11
Screenshot from 2021-04-12 16-11-08
Screenshot from 2021-04-12 16-11-04
Screenshot from 2021-04-12 16-11-01
Screenshot from 2021-04-12 16-10-51
... additional groups are also affected, but the above demonstrates it enough.

Note the truncation of the focus ring on one or both sides, depending on the group's neighboring widgets.

**Comment by mattnolting** [comment]
@mceledonia @mcarrano Hey guys, talked to @mcoker and we agreed that the safest approach to solving the focus ring issue is to define it explicitly (overwrite default browser styles) then apply a negative offset so that it always appears inside the inputs. Can you provide a focus style?

**Comment by mceledonia** [comment]
@mattnolting Check out #1824 for our last focus style, that will be a good place to start in terms of a design.

**Review by jessiehuff — APPROVED** [review]
LGTM! I think your approach here makes sense, especially given your point that the default styling across browsers can be inconsistent.

**Review by mcoker — CHANGES_REQUESTED** [review]
We discussed and decided using the xs z-index is likely a more sustainable/manageable fix.

**Comment by mattnolting** [comment]
@mcoker @garrett updated

**Review by mcoker — APPROVED** [review]
L🔥TM!

**Review by garrett — APPROVED** [review]
Looks great now! :+1: The focus ring is always above the other elements, not hidden/truncated as before.

Tested in Firefox stable, Firefox nightly (which has different default widgets now), Chrome stable, and WebKit. The focus ring is shown as it should be. (Although it's styled differently everywhere, but that's another issue. :wink:)

Thanks!

**Comment by mattnolting** [comment]
@garrett Yw! 👍  We'll work towards universal focus states ([here if your interested](https://github.com/patternfly/patternfly/issues/790))

**Pull request merged**
