### PR TITLE
fix(icons): update static icon colors

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/5395

**note:** time picker (in react) is built using the form control component, but @srambach should fix that via https://github.com/patternfly/patternfly/issues/5469 so I left that component alone here to avoid any sort of conflicts.

----

@mcarrano @mceledonia I noticed a handful of other places - do we want to update any of these? 
* Empty state icons - https://www.patternfly.org/v4/components/empty-state/html
* Multiple file upload icon - https://www.patternfly.org/v4/components/file-upload---multiple/html
* List component icons - https://www.patternfly.org/v4/components/list#with-icons

### CODE REVIEW

**Review by thatblindgeye — APPROVED** [review]
Will take another look if the other components mentioned are updated, but looks good and the icon colors update as expected when swapping between dark and light mode.

**Comment by mmenestr** [comment]
@mcoker can't believe I missed those, but I guess yes, those should be updated as well! The only one I am iffy about is the empty state because it might look really harsh, but at the same time there's not good reason why it shouldn't follow the guideline. Would you be able to show me an example before changing everything? :D 

Also, I see the changes in breadcrumb, but don't see it in the search input?

**Comment by mcoker** [comment]
@mmenestr yep, screenshots below! Re: the search input, sorry I should have mentioned that is the [text input group component](https://patternfly-pr-5526.surge.sh/components/text-input-group#utilities-and-icon-with-placeholder-text) in core. The search input component in react is built from the text input group component. The core "search input" component page is being removed.

Screenshot 2023-05-03 at 2 01 43 PM
Screenshot 2023-05-03 at 2 01 39 PM
Screenshot 2023-05-03 at 2 01 14 PM
Screenshot 2023-05-03 at 2 01 08 PM
Screenshot 2023-05-03 at 2 01 04 PM
Screenshot 2023-05-03 at 2 01 00 PM

**Comment by mcoker** [comment]
@mmenestr for the multiple file upload, I updated the main "file upload" icon color as well as the individual file icons in the progress list - but I left the spinner grey. Is that what you'd expect?

Screenshot 2023-05-03 at 9 41 10 PM

**Comment by mmenestr** [comment]
That looks good @mcoker ! Does the spinner in the upload move? Shouldn't it be blue actually? or is it just a static icon? and if it's static then in theory that should also be black yes

**Comment by srambach** [comment]
Just asking - tiles also have icons but seem to follow a different model so just checking you didn't want those to match.

**Comment by mmenestr** [comment]
@srambach tiles use black icons in their default state so I think they pretty much do follow this model, other than the fact that they become blue when the tile is selected, but I think that's fine!

**Comment by mcoker** [comment]
> Does the spinner in the upload move? Shouldn't it be blue actually? or is it just a static icon? and if it's static then in theory that should also be black yes

@mmenestr it's static - updated! https://patternfly-pr-5526.surge.sh/components/file-upload/multiple-file-upload#file-upload-status

**Review by srambach — APPROVED** [review]
👍

**Pull request merged**
