### PR TITLE
fix(nav): remove underline on hover

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/6765

### CODE REVIEW

**Review by srambach — APPROVED** [review]
Delineful!

**Review by mattnolting — APPROVED** [review]
Looks like we apply `text-decoration: none;` to the interactive element itself within several components (icon, jump-links, menu-item, simple-list-item-link, tab-link) and on `:hover/:focus` in others (breadcrumb-link, label, toggle-group). I prefer setting on the element itself, but we use both, so not a blocker. WDYT about moving to the element's default state?

**Review by andrew-ronaldson — APPROVED** [review]
You've crossed the line from awesome to super hero!

**Comment by mattnolting** [comment]
Also, should you use the semantic token `--pf-t--global--link--text-decoration` instead of `text-decoration: none`?

**Comment by mcoker** [comment]
> Also, should you use the semantic token --pf-t--global--link--text-decoration instead of text-decoration: none?

@mattnolting I don't think so, reason being `--pf-t--global--link--text-decoration` is the token/setting for a link's default text decoration. If you were to set that to something custom in an app, we wouldn't want that styling to apply to nav/other (more-button-looking links in components) on hover/focus.

**Comment by mcoker** [comment]
> Looks like we apply text-decoration: none; to the interactive element itself within several components (icon, jump-links, menu-item, simple-list-item-link, tab-link) and on :hover/:focus in others (breadcrumb-link, label, toggle-group). I prefer setting on the element itself, but we use both, so not a blocker. WDYT about moving to the element's default state?

@mattnolting nice! We should probably move the rule to the base element. If someone declared `--pf-t--global--link--text-decoration` to underline regular text links, we wouldn't want that to persist to nav and components like this that we don't want to present like text links 👍👍

**Review by srambach — APPROVED** [review]
LPTM 🚀

**Pull request merged**
