### PR TITLE
feat(menu-toggle): add transitions

### PR DESCRIPTION
**Pull request by srambach**
Adds transitions to the menu toggle.

Implements just the menu toggle part of #6590

### CODE REVIEW

**Review by mcoker — APPROVED** [review]
🐢💨

**Review by lboehling — APPROVED** [review]
lgtm!

**Review by andrew-ronaldson — APPROVED** [review]
funky cold medina

**Review by mattnolting — APPROVED** [review]
🤩 beautiful! LPTM

**Pull request merged**
