### PR TITLE
fix(global): promoted beta components

### PR DESCRIPTION
**Pull request by bonjo7**
closes https://github.com/patternfly/patternfly/issues/4119

### CODE REVIEW

**Review by mcoker — CHANGES_REQUESTED** [review]
@bonjo7 this looks great, thank you for the contribution!

A couple of requests:

* Can you remove `package-lock.json` from the commit?
* We follow [semantic release](https://github.com/semantic-release/semantic-release) for versioning, and the commit message should follow the format of something like: `fix(global): promoted beta components`. Would you mind updating the commit message as well?

Also just a tip, but we will typically [link the original issue to the PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) using kewords that automatically close the issue when the PR is merged, so that we don't have to go back and close the issue manually when a PR is merged. Feel free to do that in future contributions if you'd like!

**Comment by bonjo7** [comment]
Hi @mcoker thanks for the review and feedback. I have removed the package-lock.json and pushed the change.

**Comment by mcoker** [comment]
@bonjo7 thank you! re: `package-lock.json`, I just meant to remove the changes to it in this branch, and looks like it was removed entirely. Could you just check that file back out from master in this branch? Unless there are `package.json` updates that require an update to `package-lock.json`, we typically exclude it from the file changeset in a branch/PR.

**Comment by bonjo7** [comment]
@mcoker sorry I thought you meant for me to remove package-lock.json from the commit. There were no changes to the package.json, so do you still require to have the package-lock.json within the commit?

**Comment by bonjo7** [comment]
Ah sorry @mcoker I get you know. I have removed my previous commits and only tacked the files where the beta tag was present. That should be good now

**Comment by mcoker** [comment]
> @mcoker sorry I thought you meant for me to remove package-lock.json from the commit. There were no changes to the package.json, so do you still require to have the package-lock.json within the commit?

@bonjo7 no problem, I should have been more specific. We just need to leave the file unchanged in the commit, which looks like you've done now - thanks!! I will approve the PR once the build finishes.

**Comment by bonjo7** [comment]
No problem sorry for the confusion. My first attempt at contributing. Got there on the end :-)

**Comment by nicolethoen** [comment]
@bonjo7 
Thanks for this contribution! Throughout this sprint we are double checking all these components are truly ready for promotion, so the list of components/props to be promoted has evolved a bit since this issue was opened. I updated the list in the issue so that now the `Tile` and `NotificationDrawer` components will not be promoted at this time. Could you update this in the PR?

**Comment by mcoker** [comment]
@bonjo7 just checking in to see if you will be able to address [this comment](https://github.com/patternfly/patternfly/pull/4122#issuecomment-857822308) and add the beta flag back to the tile and notification drawer components? We have a code freeze EOD tomorrow and would like to get this PR in by then. Thanks!!

**Pull request merged**
