### PR TITLE
feat(select): added support for placeholder in toggle

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4190

examples - https://patternfly-pr-4377.surge.sh/components/select#placeholder

I added support for all of the ways you can use a placeholder in our current form select in:

core: https://codepen.io/mcoker/pen/XWgzeae
react: https://codesandbox.io/s/distracted-darkness-txput

### CODE REVIEW

**Comment by mcarrano** [comment]
@mcoker can you clarify what this PR actually does. Not sure what I am looking for. Was always a bit confused about the issue that this is to address.

**Comment by mcoker** [comment]
@mcarrano currently there are no "placeholder" styles for the select component for when the toggle is holding text that describes what to choose. From https://www.patternfly.org/v4/components/select, the toggle's "select a [whatever]" text is just regular text as a regular item in the menu. 

Screen Shot 2021-09-15 at 4 42 54 PM

This PR adds a feature to the select component to be able to style the toggle text as grey placeholder text (matches the text input and recent form select enhancement we made):

https://patternfly-pr-4377.surge.sh/components/form-control/
Screen Shot 2021-09-15 at 4 45 57 PM

https://www.patternfly.org/v4/components/form-select#invalid
Screen Shot 2021-09-15 at 4 42 13 PM


The new select placeholder examples are here - https://patternfly-pr-4377.surge.sh/components/select

**Review by mcarrano — APPROVED** [review]
Thanks for explaining this @mcoker . Looks good to me!

**Review by srambach — APPROVED** [review]
Nice update to the organization of the documentation and examples.

**Pull request merged**
