### PR TITLE
fix(modal): add support for status modifiers on title

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/6091

### CODE REVIEW

**Review by srambach — APPROVED** [review]
Looks good - is it worth saying that if the modifier is placed on the title, it will override the modifier on the modal box? I know the react component won't do this, but if someone does it, it might be confusing. Or not, I'm fine if you don't think it's necessary.
Will we phase out allowing the modifier on the modal box?

**Review by tlabaj — APPROVED** [review]
LGTM

**Comment by mcoker** [comment]
> The status modifier classes can be applied directly to the modal title element, instead of the parent modal.

@srambach probably not, just from the wording suggesting it goes on one or the other (and not both)? But I could go either way, though I may need some help wording that properly 😅

> Will we phase out allowing the modifier on the modal box?

Yeah, assuming this update works out for the next modal, it would be great to just go with a single approach. There is still a possibility adding the modifier to the title like this is too narrowly scoped (like we also want to draw a status color border around the modal or something like that), but I think we have some time to test that out before the next component is promoted and the current one is deprecated. I went back and added a beta tag to the new example so we can change it if we need to.

WDYT - good to merge or want to discuss any more updates?

**Review by srambach — APPROVED** [review]
🚀

**Pull request merged**
