### PR TITLE
feat(slider): added support for disabled

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3864

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good to me. @maryshak1996 @mceledonia what do you think?

**Comment by mcarrano** [comment]
@KKoukiou just wanted to let you know that a core PR is up. Once this is merged I think it will be ready to implement in the React component.

**Review by maryshak1996 — APPROVED** [review]

**Review by mattnolting — APPROVED** [review]
This looks great! My only question is, should the `disabled` cursor  be `not-allowed`? @mcarrano @maryshak1996?

**Comment by maryshak1996** [comment]
@mattnolting that's a really good point -- I do think that having the cursor change would make it clearer that a slider is intentionally not interactive, rather than just 'not working'

**Comment by mcarrano** [comment]
I like it. Thanks for adding the cursor disabled feature!

**Pull request merged**
