### PR TITLE
fix(log-viewer): preserved white space in log viewer text

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4396

@redallen when you have an html element in an example block, it renders a new line before the element. Is there a way we can fix that? It's messing up the formatting in some of these examples.
Screen Shot 2021-09-22 at 4 56 54 PM

### CODE REVIEW

**Review by DaoDaoNoCode — APPROVED** [review]
LGTM, thanks @mcoker !

**Review by gautamkrishnar — APPROVED** [review]

**Comment by redallen** [comment]
@mcoker Unfortunately there's no option for that in https://github.com/Prettyhtml/prettyhtml#readme . We could of course fork it and implement such an option, but some other formatting might suffer.

**Comment by mcoker** [comment]
@redallen bummer. I tried adding `<!-- prettier-ignore -->` in the examples and including `src/patternfly/LogViewer` in `.prettierignore` (though I'm guessing that's not the right path?) - didn't seem to work. Is there a way we can exclude a block or file from formatting?

**Comment by redallen** [comment]
@mcoker Sure, I could add something like that!

**Comment by redallen** [comment]
Here's a PR with it: https://github.com/patternfly/patternfly/pull/4401

**Pull request merged**
