### PR TITLE
fix(card): fixed screen-reader class on clickable card radio

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/5596

### CODE REVIEW

**Comment by srambach** [comment]
This is putting the version on the screen-reader class but it shouldn't have one, should it?
```
            <input
              class="pf-v5-c-radio__input **pf-v5-screen-reader**"
              type="radio"
              id="card-clickable-example-sr-only-radio"
              name="card-clickable-example-sr-only-radio"
              aria-labelledby="card-clickable-example"
            />
```
https://patternfly-pr-5597.surge.sh/components/card#clickable

**Comment by mcoker** [comment]
@srambach not sure if I understand.  If you're referring to `pf-v5-screen-reader`, AFAIK that does need to be prefixed - for v6 or whatever, we may change the way we apply those styles and wouldn't want conflicts with the old v5 and new v6 screen-reader class styles.

**Comment by srambach** [comment]
I thought the utility `pf-u-scrnee-reader` was prefixed, but `pf-screen-reader` was not? https://patternfly-pr-5597.surge.sh/utility-classes/accessibility

**Comment by mcoker** [comment]
If you're asking if it is currently prefixed, it's defined here:

https://github.com/patternfly/patternfly/blob/474883c523da6bf7b5bbc44dc415b2d15429565c/src/patternfly/base/_common.scss#L3

And you can see it applied in the preview

Screenshot 2023-05-18 at 12 45 42 PM

**Review by srambach — APPROVED** [review]
🤷‍♀️ OK - Then we also need to fix up the A11y documentation. And it looks like a couple other places have incorrect documentation. (calendar, popover)

**Comment by mcoker** [comment]
@srambach ah I gotcha. Also banner and input-group's docs reference `.pf-screen-reader`. I imagine those doc updates got lost in the shuffle as I don't believe the class was prefixed to begin with, then we added the prefix. Though I'd like @mattnolting to confirm whether the global classes should have the prefix or not. I'm assuming they should for the reason I gave above (along with any other kind of [global/common class](https://github.com/patternfly/patternfly/blob/v5/src/patternfly/base/_common.scss) we have like that), but Matt may know more about it than I do.

**Comment by mattnolting** [comment]
@mcoker @srambach We concluded that, because the method will potentially change in the future, `.pf-screen-reader` should be versioned. It's correct that the docs should be updated.

**Comment by mcoker** [comment]
Thanks @mattnolting! PR should be ready to review, the docs are updated.

**Review by mattnolting — COMMENTED** [review]
LPTM 👍

**Review by mattnolting — APPROVED** [review]

**Pull request merged**
