### PR TITLE
fix(global): updated sm/md icon size global vars

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3957

### CODE REVIEW

**Comment by gdoyle1** [comment]
@mcoker did this update the icons in the demos and components too? Wondering if I can tell the difference compared to what is implemented today

**Comment by mcoker** [comment]
@gdoyle1 I updated the list of elements in our components that would be impacted by changing the small and medium icon sizes in this comment - https://github.com/patternfly/patternfly/issues/3957#issuecomment-810604433

Any of those elements/icons will get the size change when they're used in component examples, demos, etc. I can provide more details on where exactly those icons are in the components if you'd like. You can compare the preview URL in this PR with what's on https://pf4.patternfly.org/ to see how the change compares to what's in the component today.

**Comment by gdoyle1** [comment]
Thanks @mcoker - I just went through them all. The only ones I noticed a _major_ difference in were the icons for the select menus and then the spinner sizes.. but I think the changes are fine! I'd like to get @mceledonia 's review as well when he's back from PTO before merging this.

**Review by gdoyle1 — APPROVED** [review]

**Comment by mcoker** [comment]
@mcarrano @mceledonia do you have any feedback? Curious if we want to consider making this change now, or queue it up for a breaking change release?

**Comment by mceledonia** [comment]
I think we might as well update these now, they are smaller so shouldn't be visually breaking. @mcarrano @mcoker

**Comment by mcoker** [comment]
> they are smaller so shouldn't be visually breaking

The small variable increases from 10px to 12px

**Comment by mcarrano** [comment]
I'd like to hold off on making this change. Looks to be low risk, but I'm wary to introduce some type of unexpected spacing or alignment effect in product. @mcoker I leave it to you as to how we want to handle this PR, but we should not merge.

I've opened https://github.com/patternfly/patternfly-design-kit/issues/371 to avoid the documentation issue by only refering to icons by size and not pixel dimensions letting these be driven by the CSS variables.

**Comment by mcoker** [comment]
> I'd like to hold off on making this change. Looks to be low risk, but I'm wary to introduce some type of unexpected spacing or alignment effect in product.

@mcarrano added the breaking change label to the original issue and will close this PR. We can redo it when we're ready to make the update.

**Pull request closed without merging**
