### PR TITLE
chore(tokens): update tokens and add chart tokens

### LINKED ISSUE #6269: Chore: Refresh tokens and add Chart tokens
Time to refresh the tokens from Figma into core. This will bring in a couple that were manually added, update some values, and add tokens for charts.

### PR DESCRIPTION
**Pull request by srambach**
Updates token variable files.
Adds chart token variables.
Updates linter to accept `--pf-t--chart`

Fixes #6269

### CODE REVIEW

**Review by mcoker — APPROVED** [review]

**Comment by srambach** [comment]
Updated a few places where the changed tokens were used.

```--pf-t--global--color--status--unread--default--active
--pf-t--global--border--width--divider--active
--pf-t--global--border--width--button--active
--pf-t--global--border--width--control--active
--pf-t--global--color--status--unread--default--active```
plus the change in pattern for `--pf-t--global--icon--size--font--body--XX` and `--pf-t--global--icon--size--font--heading--XX` (addition of `--font`)

**Review by mcoker — CHANGES_REQUESTED** [review]
Looks like there are some tokens in label group, label, progress stepper, and tile.

```diff
diff --git a/src/patternfly/components/Label/label-group.scss b/src/patternfly/components/Label/label-group.scss
index 93e400c24..330916767 100644
--- a/src/patternfly/components/Label/label-group.scss
+++ b/src/patternfly/components/Label/label-group.scss
@@ -34,7 +34,7 @@
   --#{$label-group}__label--MaxWidth: 18ch;
 
   // Close
-  --#{$label-group}__close--c-button--FontSize: var(--pf-t--global--icon--size--body--sm);
+  --#{$label-group}__close--c-button--FontSize: var(--pf-t--global--icon--size--font--body--sm);
   --#{$label-group}__close--c-button--PaddingTop: var(--pf-t--global--spacer--xs);
   --#{$label-group}__close--c-button--PaddingRight: var(--pf-t--global--spacer--sm);
   --#{$label-group}__close--c-button--PaddingBottom: var(--pf-t--global--spacer--xs);
diff --git a/src/patternfly/components/Label/label.scss b/src/patternfly/components/Label/label.scss
index 8febd186b..640c687a3 100644
--- a/src/patternfly/components/Label/label.scss
+++ b/src/patternfly/components/Label/label.scss
@@ -212,7 +212,7 @@
   --#{$label}__content--Cursor: initial;
 
   // Icon
-  --#{$label}__icon--FontSize: var(--pf-t--global--icon--size--body--sm);
+  --#{$label}__icon--FontSize: var(--pf-t--global--icon--size--font--body--sm);
 
   // Text
   --#{$label}__text--MaxWidth: 100%;
@@ -221,7 +221,7 @@
   --#{$label}__actions--MarginRight: calc(var(--#{$label}__actions--c-button--PaddingRight) * -1);
 
   // Actions button (close)
-  --#{$label}__actions--c-button--FontSize: var(--pf-t--global--icon--size--body--sm);
+  --#{$label}__actions--c-button--FontSize: var(--pf-t--global--icon--size--font--body--sm);
   --#{$label}__actions--c-button--OutlineOffset: #{pf-size-prem(-3px)};
   --#{$label}__actions--c-button--MarginTop: calc(var(--#{$label}__actions--c-button--PaddingTop) * -1);
   --#{$label}__actions--c-button--MarginBottom: calc(var(--#{$label}__actions--c-button--PaddingBottom) * -1);
```

```diff
diff --git a/src/patternfly/components/ProgressStepper/progress-stepper.scss b/src/patternfly/components/ProgressStepper/progress-stepper.scss
index cf53c7325..339982270 100644
--- a/src/patternfly/components/ProgressStepper/progress-stepper.scss
+++ b/src/patternfly/components/ProgressStepper/progress-stepper.scss
@@ -116,7 +116,7 @@ $pf-v5-c-progress-stepper--breakpoint-map: build-breakpoint-map();
   --#{$progress-stepper}--m-compact__step-main--MarginBottom: var(--pf-t--global--spacer--sm);
   --#{$progress-stepper}--m-compact__step-connector--MinWidth: #{pf-size-prem(28px)};
   --#{$progress-stepper}--m-compact__step-icon--Width: #{pf-size-prem(18px)};
-  --#{$progress-stepper}--m-compact__step-icon--FontSize: var(--pf-t--global--icon--size--body--sm);
+  --#{$progress-stepper}--m-compact__step-icon--FontSize: var(--pf-t--global--icon--size--font--body--sm);
   --#{$progress-stepper}--m-compact__step-title--FontSize: var(--pf-t--global--font--size--body--lg);
   --#{$progress-stepper}--m-compact__step-title--FontWeight: var(--pf-t--global--font--weight--body--bold);
   --#{$progress-stepper}--m-compact__pficon--MarginTop: 2px;
@@ -142,7 +142,7 @@ $pf-v5-c-progress-stepper--breakpoint-map: build-breakpoint-map();
   --#{$progress-stepper}__step-icon--ZIndex: var(--pf-t--global--Zindex--xs);
   --#{$progress-stepper}__step-icon--Width: #{pf-size-prem(24px)};
   --#{$progress-stepper}__step-icon--Height: var(--#{$progress-stepper}__step-icon--Width);
-  --#{$progress-stepper}__step-icon--FontSize: var(--pf-t--global--icon--size--body--default);
+  --#{$progress-stepper}__step-icon--FontSize: var(--pf-t--global--icon--size--font--body--default);
   --#{$progress-stepper}__step-icon--Color: var(--pf-t--global--icon--color--regular);
   --#{$progress-stepper}__step-icon--BackgroundColor: var(--pf-t--global--background--color--primary--default);
   --#{$progress-stepper}__step-icon--BorderWidth: var(--pf-t--global--border--width--box--default);
```

```diff
diff --git a/src/patternfly/components/Tile/tile.scss b/src/patternfly/components/Tile/tile.scss
index 5c9c7b259..0dcce6b19 100644
--- a/src/patternfly/components/Tile/tile.scss
+++ b/src/patternfly/components/Tile/tile.scss
@@ -17,7 +17,7 @@
 
   // icon
   --#{$tile}__icon--MarginRight: var(--pf-t--global--spacer--sm);
-  --#{$tile}__icon--FontSize: var(--pf-t--global--icon--size--body--default);
+  --#{$tile}__icon--FontSize: var(--pf-t--global--icon--size--font--body--default);
   --#{$tile}__icon--Color: var(--pf-t--global--icon--color--regular);
 
   // title
```

**Review by mcoker — APPROVED** [review]

**Comment by mcoker** [comment]
@srambach just pushed an update based on a script I wrote that will search/replace. Since we probably have some open PRs that are referencing those old tokens, we can run this script as those merge to make sure the new token names are referenced instead.

```
// manually created this file is at ~/replace (eg, /Users/mcoker/replace)
pf-t--global--border--width--control--active|pf-t--global--border--width--control--clicked
pf-t--global--border--width--button--active|pf-t--global--border--width--button--clicked
pf-t--global--border--width--divider--active|pf-t--global--border--width--divider--clicked
pf-t--global--color--status--unread--default--active|pf-t--global--color--status--unread--default--clicked
pf-t--global--icon--size--body--lg|pf-t--global--icon--size--font--body--lg
pf-t--global--icon--size--body--default|pf-t--global--icon--size--font--body--default
pf-t--global--icon--size--body--sm|pf-t--global--icon--size--font--body--sm
pf-t--global--icon--size--heading--h6|pf-t--global--icon--size--font--heading--h6
pf-t--global--icon--size--heading--h5|pf-t--global--icon--size--font--heading--h5
pf-t--global--icon--size--heading--h4|pf-t--global--icon--size--font--heading--h4
pf-t--global--icon--size--heading--h3|pf-t--global--icon--size--font--heading--h3
pf-t--global--icon--size--heading--h2|pf-t--global--icon--size--font--heading--h2
pf-t--global--icon--size--heading--h1|pf-t--global--icon--size--font--heading--h1
```

```bash
for i in `cat ~/replace`; do
  OLD=`echo $i | cut -d'|' -f1`; # stores the old token name in $OLD
  NEW=`echo $i | cut -d'|' -f2`; # stores the new token name in $NEW
  grep -rIl $OLD src/patternfly/components/ | xargs sed -i "" "s/$OLD/$NEW/g"; # grep is -r recursive, -I non-binary files, -l return only the filename where a match is found, pipe to xargs for a sed s/search/replace/g from stdin
done
```

**Comment by srambach** [comment]
Cool, thank you.

**Pull request merged**
