### PR TITLE
Add jsx for badge

### PR DESCRIPTION
**Pull request by cliffpyles**
Adds the html/jsx for the badge component

Issue: https://github.com/patternfly/patternfly-next/issues/22

### CODE REVIEW

**Comment by andresgalante** [comment]
@cliffpyles is the idea to merge this as is or for @jgiardino to patch it with the CSS?

**Comment by jgiardino** [comment]
I was going to patch with CSS.

**Comment by cliffpyles** [comment]
@andresgalante Yes, that is correct.

**Comment by cliffpyles** [comment]
@dgutride @andresgalante I don't think this is needed anymore. Care if I close it?

**Comment by LHinson** [comment]
@cliffpyles agreed, I'll close.

**Pull request closed without merging**
