### PR TITLE
fix(tabs): added overflow variation for horiz overflow variation

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/5004

### CODE REVIEW

**Review by wise-king-sullyman — COMMENTED** [review]
Looks 🔥 

Ready to approve as soon as it passes CI.

**Review by wise-king-sullyman — APPROVED** [review]
🚀

**Comment by srambach** [comment]
Now the menu can escape its container - is this going to be prevented by js? 
image

**Comment by wise-king-sullyman** [comment]
@srambach yes on the React side I'll be detecting overflowing tabs and preventing them from rendering

**Review by srambach — APPROVED** [review]
👍

**Pull request merged**
