### PR TITLE
fix(chip-group): updated all examples to use __main

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3525

### CODE REVIEW

**Review by christiemolloy — APPROVED** [review]
LGTM

**Review by mattnolting — APPROVED** [review]
Perfect!

**Review by mattnolting — APPROVED** [review]
Looks like this `__main` https://github.com/patternfly/patternfly/pull/3530/files#diff-4d67e6de46d09f5bedf56804cc395e61R359 needs backticks. Otherwise LPTM!

**Pull request merged**
