### PR TITLE
fix(accordion): made links at bottom of bordered item clickable

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4729

Added a link in the first bordered example that wasn't clickable before.

### CODE REVIEW

**Comment by evwilkin** [comment]
@mcoker this looks good to me, I see the content within the bordered content area (aka the new link) is clickable now whereas it wasn't without the `pointer-events` rule updated.

I did notice this example has no "Item four", do we want to update that as part of this PR?  If not just LMK and I'll approve 👍

**Comment by mcoker** [comment]
@evwilkin nice catch! updated.

**Comment by nicolethoen** [comment]
@adithyaakrishna - wanted to be sure this update for your issue is now in a PR :)

**Review by evwilkin — APPROVED** [review]
LGTM

**Pull request merged**
