### PR TITLE
feat(login): added support for hide/show password

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3770

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
Looks good to me @mcoker . Is this what you expected @ajacobs21e ?

My only comment is whether the names of the examples should be swapped, i..e. when the password is hidden, the action is to "show password" and vice versa.

**Comment by mcoker** [comment]
> My only comment is whether the names of the examples should be swapped

Agree, I wasn't sure, whatever you think is more intuitive. It's kind of confusing since "show password" as a description of the action's function has the password hidden, and "hide password" has the password shown. We could rename them "password hidden" and "password shown"?

**Comment by ajacobs21e** [comment]
I agree with Matt. The name is about the action not the end state.
Show password: password becomes shown (goes from hashed to text)
Hide password: password becomes hidden (goes from text to hashed)

**Comment by mcoker** [comment]
@mcarrano @ajacobs21e updated

**Review by mattnolting — APPROVED** [review]
Nice! LPTM! 🎉

**Pull request merged**
