### PR TITLE
feat(Icon): add tokens

### LINKED ISSUE #6179: Icon tokens

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
Closes #6179

[Figma design for icons](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A28&mode=design&t=doZDRUaxE4vsn5dD-1)

Convenience link: https://patternfly-pr-6205.surge.sh/components/icon

### CODE REVIEW

**Comment by lboehling** [comment]
lgtm!

**Review by lboehling — APPROVED** [review]

**Review by andrew-ronaldson — APPROVED** [review]
Ship it!

**Review by srambach — APPROVED** [review]
👌 beautiful! Thank you for working through this.

**Review by kmcfaul — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
🍕🐢

**Pull request merged**
