### PR TITLE
fix(labelgroup): add close button to the top right always

### LINKED ISSUE #3456: Label Group: Move close button to top-right for vertical group
For a vertical Label group, move the Close button to the top right (rather than bottom). Wrapping a horizontal group should have the same effect. Goal is to have consistency/parity with what we do for the Chip group.

### PR DESCRIPTION
**Pull request by christiemolloy**
closes #3456

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good to me. Thanks @christiemolloy !

**Review by mcoker — APPROVED** [review]
LGTM!

**Review by mattnolting — APPROVED** [review]
Perfecto!

**Pull request merged**
