### PR TITLE
feat(TabContent): consumed Penta tokens

### PR DESCRIPTION
**Pull request by thatblindgeye**
Work towards #5711

### CODE REVIEW

**Review by srambach — APPROVED** [review]
Preview is still down, but the code looks 💯

**Review by andrew-ronaldson — APPROVED** [review]
Ship it!

**Review by mcoker — APPROVED** [review]
LGTM! Just to confirm - the tab content previously did not have a background color specified by default, so it would be transparent and the background would come from whatever it's placed inside of. Now the default background is our primary background color, with the secondary variation for a secondary background color.

Is that the intention, or should it just be transparent by default? @andrew-ronaldson

**Comment by mcoker** [comment]
Verified with @andrew-ronaldson that we should just use a transparent background by default.

**Pull request merged**
