### PR TITLE
fix(sidebar): changed split/stack to horizontal/vertical

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4146

### CODE REVIEW

**Comment by srambach** [comment]
This seems a little confusing when compared to the drawer, which uses `.pf-m-vertical` and `.pf-m-horizontal` to describe the splitter orientation, which would be the opposite of how it is used here for the orientation of the content and sidebar. Where you already have a `.pf-m-panel-right` modifier, what about somehow making this consistent with how drawer uses `.pf-m-panel-left` and `.pf-m-panel-bottom` modifiers?

**Comment by mcoker** [comment]
> This seems a little confusing when compared to the drawer, which uses .pf-m-vertical and .pf-m-horizontal to describe the splitter orientation, which would be the opposite of how it is used here for the orientation of the content and sidebar.

If I understand correctly, I think that's going to be the case since the splitter is horizontal when used in a vertical (top/bottom) drawer layout, and it's vertical when used in a horizontal (left/right) drawer layout. I would expect it to be used the same here, too - vertical splitter with horizontal/left/right sidebar, horizontal splitter with vertical/top/bottom sidebar.

> Where you already have a .pf-m-panel-right modifier, what about somehow making this consistent with how drawer uses .pf-m-panel-left and .pf-m-panel-bottom modifiers?

Are you suggesting the default orientation of this layout and the drawer match? (panel-right by default?) Or dropping horizontal/vertical and just using side (top, left, right, bottom) modifiers? Or maybe something else?

**Comment by srambach** [comment]
I see what you mean about the "splitter" orientation. I think this is confusing because what you think of as a vertical sidebar here is using the horizontal modifier, because it's actually modifying the _layout_. This is so similar in concept with the drawer, I think as much consistency as possible would be good, so yeah, maybe the top/bottom/left/right would be more clear?
image

**Comment by mcoker** [comment]
@mcarrano wdyt about the naming for this? Currently we're the variations for this component "horizontal" and "vertical" depending on whether the panel/content are side by side or the panel is stacked on top of the content. To @srambach's point, this can be confusing since we call it a "sidebar" component, and in the horizontal variation, the sidebar is vertical - and vice versa.

**Comment by mcarrano** [comment]
@mcoker @srambach I really don't know what to say. Has anyone else complained that this is currently confusing? Was there a problem with "stacked" and "split"? I agree horizontal and vertical are confusing terms here.

**Comment by mcoker** [comment]
@mcarrano I haven't heard any feedback about it. We were just trying to be consistent in our prop/value naming after implementing vertical/horizontal description list groups - https://github.com/patternfly/patternfly-react/pull/5885#pullrequestreview-680119708

I'm fine with leaving it as split and stack, too, since "vertical" can be confusing here. We use split and stack in other contexts, too - split/stack layouts, "stack" tile header, and "stack" form groups for stacking multiple form control elements.

**Comment by mcoker** [comment]
Closing this for now since this isn't solving an obvious problem and could lead to more confusion.

**Pull request closed without merging**
