### PR TITLE
docs(button): adds demo for progress button completion state

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4354

### CODE REVIEW

**Comment by ajacobs21e** [comment]
@mcoker The button part looks good, thank you!

@mcarrano is there a standard set of dummy data we use for demos? I don't think we should use "Red Hat login" or my name in the example.

**Comment by mcoker** [comment]
@ajacobs21e I changed it to something more generic - does this look ok?

Screen Shot 2021-11-17 at 4 27 19 PM

**Comment by ajacobs21e** [comment]
@mcoker yes that's better! Can you make username a default input and put ***** in the password field so it looks like the form has been completed please?

**Review by mcarrano — COMMENTED** [review]
@mcoker I don't have any comments beyond what @ajacobs21e has already flagged. But I am curious why we need the beta feature heading on the Demo page. Is that needed for something that's just a demo?

**Comment by mcoker** [comment]
@mcarrano @ajacobs21e updated. The beta flag is just part of the new demo template - removed it.

**Comment by ajacobs21e** [comment]
LGTM! @mcarrano are you ok with the button text "link account and log in"? There's probably something more generic we could use but I am blanking on a better suggestion. It probably doesn't matter.

**Review by mcarrano — APPROVED** [review]
I think that the example text is fine @ajacobs21e . This looks good to me! Thanks @mcoker .

**Review by ajacobs21e — APPROVED** [review]

**Pull request merged**
