### PR TITLE
fix(label): add tokens

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/6181

--

TODO - still need to add states (success, error, etc)

### CODE REVIEW

**Review by andrew-ronaldson — COMMENTED** [review]
These look great.
I saw the beta label has this hover state. @lboehling any thoughts? Screenshot 2024-01-12 at 11 06 07 AM

**Comment by mcoker** [comment]
@andrew-ronaldson looks like it's in a plain button, which looks to just be just for the tooltip? I created an org issue to fix that - https://github.com/patternfly/patternfly-org/issues/3859

**Comment by srambach** [comment]
The close button just slightly overlaps the text - is that ok or do we want a little more space? 
image

The focus outline in conjunction with the label shape is a little weird overall but I understand why and don't have any better ideas. :-) 
image

**Review by srambach — APPROVED** [review]
Other than the focus outline, which can be adjusted later if we want, looks 👌

**Review by andrew-ronaldson — APPROVED** [review]
Perfecto!

**Pull request merged**
