### PR TITLE
feat(menu): added variation for top and left flyout menus

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3938

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks great @mcoker . Will there be changes required to the React component to flip the menu orientation or do we get this for free?

**Comment by mcoker** [comment]
@mcarrano there will be react updates.

**Comment by mcoker** [comment]
@mcarrano also added [top aligned](https://patternfly-pr-3977.surge.sh/components/menu#with-flyout-menu-top) and [top left aligned](https://patternfly-pr-3977.surge.sh/components/menu#with-flyout-menu-left-top)

**Comment by mcarrano** [comment]
@mcoker I do have a question about the top alignment. What is that positioning aligning to?

**Comment by mcoker** [comment]
Basically instead of the menu expanding down, it expands up. It aligns with the bottom of the item that it flies out from.

Screen Shot 2021-04-07 at 1 31 36 PM
Screen Shot 2021-04-07 at 1 31 46 PM

**Comment by jschuler** [comment]
I agree, it's good to have these CSS options if the position can be pre-determined, otherwise in react we can let popper position it for us, it might look something like this:
Screen Shot 2021-04-07 at 3 17 52 PM

**Comment by mcoker** [comment]
@jschuler thanks! Sounds like we'll need a react issue for that work (I don't see one currently) and can use these updates in core to help with the popper implementation re: positioning/alignment?

**Review by mattnolting — APPROVED** [review]
LPTM! 🥇

**Pull request merged**
