### PR TITLE
feat(multiplefileupload): added component

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4521

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
This is looking good @mcoker . Just a couple comments...
* Can we rename this to something more like "File upload - multiple?" That way it will be easier to find in the navigation when someone looks for file upload.
* Is what I am seeing here for the horizontal the actual fixed width? Is that consistent with the design?
* Shouldn't there be a layout that includes one or more progress bars that show status of the upload in progress?

**Comment by mcoker** [comment]
@mcarrano looks like you reviewed before the build was finished. Check again and let me know what you think.

Also there are 2 bugs outstanding. From 
Screen Shot 2021-12-01 at 5 32 24 PM

I'm not sure how to present a long file name and align the progress percentage text (eg, "35%"). That percentage text is aligned bottom by default in the progress component. Should I make an update?

Long text in the progress area causes the horizontal/fixed width layout width to increase. Still working to address that.

**Comment by mcarrano** [comment]
Another solution would be to just truncate the filename if it exceeds the available space. Seems like this would be a pretty rare occurrence.

**Review by mcarrano — APPROVED** [review]
This looks great @mcoker I know there are a couple of loose ends. Feel free to open a follow-up issue if needed and we'll look to move this to React in the next milestone.

**Review by mattnolting — APPROVED** [review]
> This looks great @mcoker I know there are a couple of loose ends. Feel free to open a follow-up issue if needed and we'll look to move this to React in the next milestone.

+1 LGTM

**Pull request merged**
