### PR TITLE
fix(page): adjust main container and sidebar scrollbars

### PR DESCRIPTION
**Pull request by mcoker**
towards https://github.com/patternfly/patternfly-design/issues/1315

### CODE REVIEW

**Review by andrew-ronaldson — COMMENTED** [review]
I checked this in Chrome, firefox and Safari. Safari is the only one that keeps the scrollbar background-color. Would this `::-webkit-scrollbar-track:` work to tackle the safari issue.

Other than that I think this looks great and Safari is a lower priority browser

**Comment by mcoker** [comment]
@andrew-ronaldson yep, the controls for safari scrollbar colors are a little different, and seem to be finicky? Here's a codepen with the overrides in it. https://codepen.io/mcoker/pen/LYKvOgW

You can see in safari that the sidebar scrollbar styles are working, but not on the page main container. If we update the `.pf-v6-c-page__main-container` to be `display: block` instead of `display: flex`, the scrollbar styles work? IMO that shouldn't impact the scrollbar styles at all.

Also, I'm assuming if we were to introduce custom scrollbar styles, we would do it for all scrollbars - not just the sidebar/page container?

I went ahead and took out the scrollbar changes from this PR - wdyt about merging these changes and following up on the scrollbar stuff, either for final or post-v6, but that would let us get these other changes in now.

**Review by lboehling — APPROVED** [review]
beautiful!!

**Review by thatblindgeye — APPROVED** [review]
Would this go towards https://github.com/patternfly/patternfly/issues/6834 at all, too?

**Review by andrew-ronaldson — APPROVED** [review]
This looks good in the main container. The floating track next to the nav feels awkward but can be addressed your followup issue. Thanks!

**Review by srambach — APPROVED** [review]
📜 Looks good, nice work with design

**Pull request merged**
