### PR TITLE
fix(button): allowed inline link text to wrap and use with span element

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3313

### CODE REVIEW

**Comment by mcoker** [comment]
@christiemolloy re: @jenny-s51's comment

> can we update the hint example with the new modifier?

Does the button in the hint example need to be a button, or could that just be a link?

**Comment by christiemolloy** [comment]
> @christiemolloy re: @jenny-s51's comment
> 
> > can we update the hint example with the new modifier?
> 
> Does the button in the hint example need to be a button, or could that just be a link?

I think the dropdown button and the buttons in the footer are meant to buttons, but link would go in the body paragraph in the hint . hopefully that answers the question :)

**Comment by mcoker** [comment]
> link would go in the body paragraph in the hint

Great, agreed, thanks! Updated that example @christiemolloy @jenny-s51

**Review by mattnolting — APPROVED** [review]
Nice work @mcoker! I can see where this is needed. ~~@christiemolloy The hint component in the SS should be a standard link though, right?~~ I see you already discussed this..

**Review by christiemolloy — APPROVED** [review]
LGTM! conflict

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/3470

**Pull request closed without merging**
