### PR TITLE
chore(a11y): enable attr check, update modal and popover

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4963

### CODE REVIEW

**Review by jessiehuff — APPROVED** [review]
LGTM! :)

**Comment by mcoker** [comment]
@mcarrano - FYI this updates the modal and popover examples to be full page examples.

https://patternfly-pr-4977.surge.sh/components/modal/
https://patternfly-pr-4977.surge.sh/components/popover/

**Review by mcarrano — COMMENTED** [review]
@mcoker Can we center these in the full page window?

**Comment by mcoker** [comment]
@mcarrano yep, updated

**Review by mcarrano — APPROVED** [review]
Yep. Much better. Thanks @mcoker !

**Review by srambach — APPROVED** [review]
👍

**Pull request merged**
