### PR TITLE
chore(select): fixed text in HTML example to show multiple checks can be selected

### PR DESCRIPTION
**Pull request by ashley-o0o**
Fixed some of the hidden labels in the HTML examples on Select page. Some were saying to choose one when multiple could be selected. Adjusted to reflect that.

Closes: [#5653](https://github.com/patternfly/patternfly/issues/5653)

### CODE REVIEW

**Comment by srambach** [comment]
Nice fix! ⭐ I see one inconsistency that didn't get covered, but I'm not sure if it's really supposed to be multiple:
This example shows multiple items selected, but uses "Choose one" - I'm not sure whether this should have the label fixed or remove the multiple selections, since the next example shows multiple selection with checkboxes. https://patternfly-pr-5663.surge.sh/components/menus/select#item-description

**Comment by srambach** [comment]
This is great - one thing though I think it might be better to make the one that is selected to be one of the options that has a description - that way it demonstrates the alignment with the description. What do you think?

**Comment by mcoker** [comment]
@ashley-o0o +1 to @srambach's comment, I think showing how the checkmark aligns with an item with a description would be a nice add for this example.

**Comment by mcoker** [comment]
@ashley-o0o looks like you've got a couple of conflicts. In https://github.com/patternfly/patternfly/pull/5667, the `src/patternfly/components/Select/examples/*` files were moved to `src/patternfly/components/Select/deprecated/`, so your changes to those files are conflicting. Let me know if you need help resolving that 👍

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
This is looking nice! Just had a couple other examples that'd be worth updating a bit further:

- [Single with typeahead expanded](https://patternfly-pr-5663.surge.sh/components/menus/select#single-with-typeahead-expanded) has the hidden text as "New", which makes the listbox announced as "New listbox..." rather than "Choose a state listbox...".
- "Single with typeahead expanded and selected" and "Multi with typeahead (chip group collapsed)" examples have a similar issue, where the text of the input is being used as the hidden label text

Something else I'm noticing that I can open a follow-up for is adding `aria-selected="false"` to any items that aren't selected, as well as updating the documentation wherever `aria-selected="true"` is documented. With VoiceOver right now even non-selected items are announced as "[item text], selected".

**Review by thatblindgeye — APPROVED** [review]
I opened the above-mentioned followup issue

**Review by mcoker — APPROVED** [review]

**Pull request merged**
