### PR TITLE
chore(deps): updated commitlint, stylelint, prettier

### PR DESCRIPTION
**Pull request by mcoker**
resolves some of https://github.com/patternfly/patternfly/issues/5119

made breaking change notes to fix using `:not()` as changing `:not(.foo):not(.bar)` to `:not(.foo, .bar)` will change the specificity from 20 to 10. From https://developer.mozilla.org/en-US/docs/Web/CSS/:not

> _The specificity of the :not() pseudo-class is replaced by the specificity of the most specific selector in its comma-separated argument of selectors; providing the same specificity as if it had been written [:not(:is(argument))](https://developer.mozilla.org/en-US/docs/Web/CSS/:is)_

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]
this seems good to me

**Comment by srambach** [comment]
Are the @import url() changes meant to be part of this PR?

**Comment by mcoker** [comment]
@srambach yep, the `url()` function isn't needed with an `@import` statement, the URL can just be passed as a string.

**Comment by srambach** [comment]
> @srambach yep, the `url()` function isn't needed with an `@import` statement, the URL can just be passed as a string.

k, just checking it didn't slip in from another since it wasn't mentioned in the description or issue.

**Review by srambach — APPROVED** [review]

**Pull request merged**
