### PR TITLE
fix(notification-drawer): fix action alignment, add no-offset mod

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/6577

### CODE REVIEW

**Review by andrew-ronaldson — APPROVED** [review]
Stupendous!

**Comment by evwilkin** [comment]
Two questions:
1. The initial alignment problem from the issue looks fixed, but is the `.pf-m-no-offset` example as intended?  The action button looks to be top-aligned with the header text, but due to the size it looks to overlap down to the line of text below:
Screenshot 2024-07-05 at 9 58 28 AM

2. Also wanted to check if the second note in the original issue description about replacing `margin-block-end` with `row-gap` needs to be addressed before that issue is closed out or if that should be disregarded?

**Review by srambach — APPROVED** [review]
@evwilkin it looks like it was already changed to use gap.
I agree that the example with the primary button actually looks better without the `f-m-no-offset` because then the text aligns. But the modifier is working as expected, so if needed, looks good.

image

**Review by evwilkin — APPROVED** [review]
Based on @srambach's notes, LGTM 👍

**Pull request merged**
