### PR TITLE
fix(icons): added task icon to pficons

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4165

Icons page - https://patternfly-pr-4184.surge.sh/icons/

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good to me!

**Review by gdoyle1 — APPROVED** [review]
LGTM!

**Comment by gdoyle1** [comment]
@mcoker @mcarrano question - will this also be added into the React set of icons? I'm creating an issue to add this icon to the Icons table on patternfly.org and was hoping to get the react_name

**Comment by mcoker** [comment]
@gdoyle1 yes, it should be called `TaskIcon`

**Comment by gdoyle1** [comment]
@mcoker sweet, thanks!!

**Pull request merged**
