### PR TITLE
feat(menu): added scrollable and plain modifiers

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4027

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
I think that the basic plain version without the border looks great. It does get a little weird with the search and the footer when you remove the outer boarder. What do you think @garrett . Maybe we would remove all borders/dividers? But then the scroll bar floats.

@mceledonia can you also take a look?

**Comment by mceledonia** [comment]
It looks good to me, for the search/footer version I'm thinking given that it will appear in some other context it should work out. Do you have any examples of where that would be used? I'm having a tough time visualizing it.

**Comment by mcoker** [comment]
@mcarrano @mceledonia, @garrett has an example in the original issue - https://github.com/patternfly/patternfly/issues/4027#issuecomment-826896486

Ideally the menu will be in some kind of context box where it will make sense if the menu is scrollable. The only thing I think looks weird is that the footer currently always has a box shadow. If the menu isn't scrollable, it looks like this:

Screen Shot 2021-09-21 at 12 38 33 PM

We could probably solve that by creating a variation for a scrollable menu, which we aren't doing now. A currently user makes the menu scrollable by passing a height to the content area instead of opting into a scrollable variation. If we had a scrollable variation, we could remove the shadow on the footer and use a border there instead, both in this plain variation as well as the regular menu.

Here's what the regular menu looks like now with a footer when the content isn't scrollable:

Screen Shot 2021-09-21 at 12 40 34 PM

And here's what my proposed change would look like:

Screen Shot 2021-09-21 at 12 40 58 PM

This would also allow us to set a reasonable default max-height for the scrollable menu, and the user could override that if they want something different. Currently if they want a scrollable menu, they have to set the max-height manually (there is no default).

cc @mattnolting wdyt?

**Comment by mcarrano** [comment]
@mcoker I agree that the single line divider makes more sense than the shadow. Interested to hear what others think.

**Comment by garrett** [comment]
For what it's worth, here's how our override looks in Cockpit, in the (filterable) language selector dialog:

Screenshot 2021-09-22 at 10-29-16 Overview - garrett Bolt

Screenshot 2021-09-22 at 10-29-31 Overview - garrett Bolt

We don't have extra borders around anything. It's styled like a search input plus a scrollable, selectable region (with a border around it, otherwise it would look broken).

**Comment by mcoker** [comment]
@mcarrano updated the component to:

* Add a "scrollable" variation - by default when the variation is enabled, the menu height is 300px. Added new examples of that.
* Made the menu footer have a top border by default instead of a box shadow.
* When the menu is set to the scrollable variation, the footer has a top shadow and bottom border.

**Comment by mcarrano** [comment]
I think this looks much better @mcoker . Only one small nit. Shouldn't the divider above the scrollable list also have a shadow in this example? https://patternfly-pr-4392.surge.sh/components/menu/#plain-scrollable-with-search-and-footer  What do you think @mceledonia ?

**Review by mcarrano — APPROVED** [review]
Please disregard my last comment. This is good to go. Thanks @mcoker !

**Review by srambach — APPROVED** [review]
Looks great!

**Pull request merged**
