### PR TITLE
feat(jumplinks): add demo

### LINKED ISSUE #3560: Introduce jump links demo
Create a demo that shows placement of the jump links/scrollspy navigation inside of a page for both horizontal and vertical variants. See designs here: https://github.com/patternfly/patternfly-design/issues/792

### PR DESCRIPTION
**Pull request by christiemolloy**
closes #3560 

@mcoker @mattnolting what do you guys think about adding a new section in the page to handle the jump links? it looks like in these designs: https://www.sketch.com/s/e6c01dec-8567-436c-b633-eda045100a37/a/Zz2AnY the section needs no top or bottom padding 
Screen Shot 2020-11-03 at 3 36 25 PM

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
Looks good to me @christiemolloy , but what about responsive behavior? What do we expect to happen when we shrink the page down? I think this was addressed in the design.

@lboehling can you also take a look?

**Comment by mattnolting** [comment]
@christiemolloy I can see this demo going two ways

`pf-c-page__main-section.pf-m-jump-links` or `pf-c-page__main-section.pf-m-no-padding.pf-m-inset-xx`

Regardless, I think we should consider adding `insets` to `pf-c-page__main-section`, which may be a separate issue. We could potentially add `insets` in another PR and consume them here...

**Comment by mcoker** [comment]
Should the vertical jump links have the ability to remain sticky? Would we want to support something like this?

72051351-0e3a3880-32fe-11ea-8003-bb4b85685484

It also seems like you should be able to have the vertical jump links adjacent to main sections. In the demo, jump links are beside a content component. I was expecting a user to take an existing page with multiple sections, and have a jump links element positioned to the left or right, and come before all of the page sections it links to in the markup. Kind of like an inline drawer.

To be able to reposition and lay out the jumplinks to the top of the page and as a dropdown per the responsive designs, it seems like we'll need a page component layout to take a content section (the page sections) and jump links component that presents them side by side and allows for the jump links to be sticky or not, and allows the user to switch the layout to a responsive view at a prescribed breakpoint that would move the jump links above the content section, and switch the jump links layout to a mobile layout.

That's just how I envisioned it from looking at the designs, what do y'all think?

And yeah I think it's fair for the jump links to have it's own page section, which gives the user the ability to put it wherever they want. If it follows the react page component sections, `jumpLinks` or something like that would be the prop that a user passes to the page component and we insert it automatically (like we do with tertiary nav and breadcrumbs). Then we would have a `<PageJumpLinks />` component if the user constructed it themselves, like [<PageNavigation](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Page/PageNavigation.tsx) and [<PageBreadcrumb>](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Page/PageBreadcrumb.tsx).

**Comment by mcarrano** [comment]
These are good questions @mcoker I've scheduled some time to discuss. I think this is very related to the request here: https://github.com/patternfly/patternfly/issues/3255 also.

**Pull request closed without merging**
