### PR TITLE
Fixes #4854  fix(notification-badge): fixes documentation links

### LINKED ISSUE #4854: Broken links in docs
when crawling through the workspace in the a11y report, the following broken links were discovered:

- [Checkout our upgrade guide for a list of breaking changes!](https://www.patternfly.org/v4/developer-resources/release-notes/#2020.07-release-notes-2020-06-05) should point to '/developer-resources/upgrade-guide'
- [This component is designed to be used within a dark component such as the masthead.](https://www.patternfly.org/v4/components/notification-badge/html#overview) should point to 'components/masthead'
- [Note: The page component currently handles the selected state styling...](https://www.patternfly.org/v4/components/notification-badge/html#overview) should point to '/components/page'

### PR DESCRIPTION
**Pull request by blfetche**
Fixes #4854

fix(notification-badge): fixes documentation links

### CODE REVIEW

**Comment by srambach** [comment]
Great job getting your first PR in! 🎉 
Is there one more link to fix in RELEASE-NOTES.md, way down in the 2020.7 section?

**Comment by blfetche** [comment]
@srambach recommitted an update to release-notes.md to correct the upgrade links issue

**Review by srambach — APPROVED** [review]
Looks great to me! ✨

**Comment by blfetche** [comment]
Thanks again @srambach for all your help in getting me this far :)

**Pull request merged**
