### PR TITLE
fix(table): removed extra padding from nested table cells

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4280

### CODE REVIEW

**Comment by mcarrano** [comment]
Is this the example I should be looking at @mcoker ? https://patternfly-pr-4529.surge.sh/components/table#expandable-with-nested-table-example  I thought the intent was to remove padding, but in the example looks like the nested table has even more padding.

**Review by mattnolting — APPROVED** [review]
LPTM

**Comment by mcoker** [comment]
@mcarrano yep that's a new example showing a simple table nested in expandable content. That extra padding is coming from the expanded content element. Updated it to remove all of that padding and just have standard padding. Another example to look at is compound expansion, since that includes a nested table - https://patternfly-pr-4529.surge.sh/components/table/#compound-expansion-example

If we have a better use case/design for a nested table I can use to modify the example I added, let me know and I'll update it.

**Comment by mcarrano** [comment]
Yes, this looks much better @mcoker . Is this what you were expecting @KKoukiou ?

**Comment by KKoukiou** [comment]
> Yes, this looks much better @mcoker . Is this what you were expecting @KKoukiou ?

Indeed! The new example is what I would expect! Thanks for fixing this!

**Pull request merged**
