### PR TITLE
fix(datalist): adjust action elements, spacing

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/7079

This removes `__action`, which was only used to wrap plain actions and give them a negative top/bottom margin, and adds that negative offset to `__item-action` so it will apply to all actions. Got design approval for the change in https://github.com/patternfly/patternfly-react/pull/10939#issuecomment-2347830104

### CODE REVIEW

**Comment by mcoker** [comment]
@tlabaj d'oh! Yep, forgot to update the handlebars to remove that element. Updated 👍

**Review by thatblindgeye — COMMENTED** [review]
There's some usage of the removed data-list-action component in some of the examples in the markdown file, otherwsie lgtm

**Comment by mcoker** [comment]
@thatblindgeye thanks! Updated 🚀

**Review by thatblindgeye — APPROVED** [review]

**Review by srambach — APPROVED** [review]
Looks good 🎃

**Pull request merged**
