### PR TITLE
feat(label): add support for overflow

### LINKED ISSUE #3259: Label - support overflow ellipsis and tooltip
**Describe the issue. What is the expected and unexpected behavior?**

_Unexpected_: Labels that have long character strings grow indefinitely.
Screen Shot 2020-07-01 at 2 25 34 PM

_Expected_: Labels follow the same behavior as Chips - truncate long text, show an ellipsis and tooltip.
Screen Shot 2020-07-01 at 2 24 30 PM

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Create a label with a large number of characters

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
Tower 
cc @trahman73

### PR DESCRIPTION
**Pull request by christiemolloy**
closes #3259

### CODE REVIEW

**Comment by mcoker** [comment]
@mcarrano @mceledonia would you consider this change visually breaking? Wondering if this should be opt-in, or just the new default for labels.

**Comment by mcarrano** [comment]
I don't consider it visually breaking. Why wouldn't you want this? What do you think @mceledonia ? Also, isn't the Label component still beta?

**Comment by mcoker** [comment]
@mcarrano a potential implication is if there are labels currently that exceed the width, the content that is currently visible will not be without having to hover the label to see a tooltip, and that could be unwanted. I think it's fine, since it sounds like it was an oversight not to have it in the first place, so it's more of a bug fix. I just wanted to clarify since the way we make the update in react could depend on wither a prop enables it or not.

**Comment by mcarrano** [comment]
@christiemolloy @mcoker I'm kind of torn on this one. I guess there could be cases where you would not want the label to truncate. Let me get some other design opinions. @mceledonia @maryshak1996 @kybaker @gdoyle1 what do you think? In your usage of labels, are there cases where you might not want a long label name to truncate?

**Pull request merged**
