### PR TITLE
fix(wizard): set in page wizard page section to shrink so footer/nav are sticky

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3255

@mcarrano this adds a top box-shadow to the wizard footer when the wizard is 1) used in a modal, 2) used in the special page component section currently needed to add the wizard to the page. Those are the places where we should be able to guarantee the wizard footer remains sticky, so a shadow seems appropriate. I didn't add it globally to any wizard footer since, if the footer doesn't remain sticky as it should, the shadow will look out of place. So this means we may end up with some wizard footers that have a shadow, and ones that don't, even if the wizard footer is sticky since the wizard wasn't used in a modal or the special page section. That seems like a fair compromise since the wizard footers don't have a shadow currently, so nothing changes there. WDYT about that? Should we just wait and add a shadow to the footer in a breaking change to avoid a potential inconsistency with some footers having a shadow, and some not?

### CODE REVIEW

**Review by DaoDaoNoCode — APPROVED** [review]
Thanks @mcoker , codes LPTM!

And I agree that we should only add box shadow on wizard in pages and modals. For basic examples, adding a box shadow on footer seems a little bit weird for me when I apply `var(--pf-global--BoxShadow--sm-top)` to it.

Screen Shot 2021-02-01 at 5 18 51 PM

There is a small shadow on the right side. When I apply `var(--pf-global--BoxShadow--md-top)` to it, the shadow on the right disappears, while the top shadow seems too large.

Screen Shot 2021-02-01 at 5 24 11 PM

In my opinion, currently adding box shadow only to the places where we need may be the best choice to avoid breaking changes.

**Comment by mcarrano** [comment]
@mcoker @DaoDaoNoCode I have a couple of questions about this. I thought that the original goal was to make the left-hand steps panel as well as the footer sticky so only the body scrolls. From the title of this PR, looks like it only addresses the footer? From the examples I can't really tell what happens to the siderbar.

Also, I basically agree with you regarding the application of the shadow. However it's visually odd that the footer has a shadow but the left panel does not. Should they have the same effect? I don't know. @mceledonia I'd like to get your opinion here, also.

**Comment by mcoker** [comment]
@mcarrano updated the description - the problem was that the in page wizard was growing too tall, when it needs to shrink to conform with the main page area height. I didn't make any adjustments to the nav - just fixed the wizard's page section so that it shrinks to only fill the available space.

I also updated the wizard examples/demos with a basic form to fill the content area and allow us to text the overflow/scrolling behavior. Does that look OK or would you prefer leave those examples empty?

**Review by mcarrano — COMMENTED** [review]
Thanks @mcoker . Adding the form inside the wizard body makes it much easier to see whaty is going on. But I still have the same question for @mceledonia about the box shadow.

**Review by mattnolting — COMMENTED** [review]
Looks great, one question. Should we set `min-height` on `.pf-c-wizard__inner-wrap` for this scenario?

Screen Shot 2021-02-09 at 10 41 50 AM

Or would nobody ever use a browser this way, which is entirely possible..

**Comment by mcoker** [comment]
> Should we set min-height on .pf-c-wizard__inner-wrap for this scenario?

I wondered the same thing... it seems like a safe add, though I also wonder if we should just leave it to the user to make sure there is enough room for the wizard to show the content. @mcarrano wdyt?

**Comment by mcarrano** [comment]
@mcoker @mattnolting I think setting a `min-height` makes sense. So what would happen in the scenario about then?

**Comment by mcoker** [comment]
@mcarrano the footer actions would be pushed down and not sticky if the viewport height was less than the min-height. Once the viewport height was greater than the min-height, the footer would become sticky again.

**Comment by mcarrano** [comment]
Makes sense to me @mcoker .

**Comment by mcoker** [comment]
@mattnolting updated the `min-height`

**Review by mattnolting — APPROVED** [review]
Beautiful, LPTM 🎉

**Pull request merged**
