### PR TITLE
fix(toolbar): Do not hide labels in collapsed state

### LINKED ISSUE #4284: Toolbar hides labels in collapsed state
Using example: https://www.patternfly.org/v4/components/toolbar/react/stacked-example/
Changing browser size so toolbar is collapsed it looks like this:
Screenshot from 2021-08-11 14-40-10

Labels for all selects are not displayed. This seems odd, as for someone who only sees this collapsed state (like mobile users) would have hard time understanding what these selects do.

Removing [THIS](https://github.com/patternfly/patternfly/blob/main/src/patternfly/components/Toolbar/toolbar.scss#L338) rule makes it look like this, which seems much more user friendly:
Screenshot from 2021-08-11 14-40-30

I would even send PR with removal of this one rule, but I feel like I am not understanding why it was introduced in the first place.

### PR DESCRIPTION
**Pull request by marusak**
Fixes #4284

See #4284 for before and after.

### CODE REVIEW

**Comment by mcoker** [comment]
Hi @marusak just wanted to check in and see if my suggestion made sense? Let me know if you need any additional information.

**Comment by marusak** [comment]
Sorry for taking too long to update this PR. Your suggestions work like a charm and it indeed looks much better! Thank you :)

**Review by mcoker — APPROVED** [review]
LGTM! @mcarrano would you mind re-reviewing?

**Review by mcarrano — APPROVED** [review]
Looks great @mcoker @marusak !

**Pull request merged**
