### PR TITLE
feat(expandable-section): added truncate variant

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4881

### CODE REVIEW

**Review by mmenestr — APPROVED** [review]
LGTM!

**Review by mattnolting — APPROVED** [review]
LPTM!

**Review by mcarrano — COMMENTED** [review]
@mcoker This looks good, but I just have a couple of comments/questions:

* Now that I see this, I'm questioning whether we should have the caret icon in front of the button (change from what I said before). When I see that, I immediately think that the content will expand below. Maybe we should remove that and just have the text? What do you think @mmenestr ?
* I don't really like the naming of this. What is we call it "Truncated text area" or "Expandable text block"?

**Comment by mcoker** [comment]
> Now that I see this, I'm questioning whether we should have the caret icon in front of the button

@mcarrano I agree, though it's worth noting that it will have a smaller clickable target area if we use the inline link button (no padding), which would remove the left padding and allow the button text to be aligned to the left of the expandable text.

> When I see that, I immediately think that the content will expand below.

It's also worth noting that I flipped the caret icon when expanded, since the default use case would be to expand content above the toggle. This matches our pre-existing detached toggle example. https://patternfly-pr-5001.surge.sh/components/expandable-section#detached-toggle

> What is we call it "Truncated text area" or "Expandable text block"?

Sure, though the variation name is currently "truncate" (`pf-m-truncate`) - do you think that's confusing, or is it just the example name? "text area" also somewhat implies a `<textarea>` (a multi-line form input). What about "Truncated text"?

**Comment by mcarrano** [comment]
> Sure, though the variation name is currently "truncate" (pf-m-truncate) - do you think that's confusing, or is it just the example name? "text area" also somewhat implies a <textarea> (a multi-line form input). What about "Truncated text"?

I'm concerned that people might confuse this with the Truncate component. Maybe "Truncated text" is OK. @mmenestr what do you think?

**Comment by mmenestr** [comment]
@mcarrano I don't mind with caret or without, like @mcoker said, the direction of the arrow matches the direction of the text so I don't think it really matters where it's pointing.. but I get the appeal of just having a link button as well.

In terms of the naming, could we maybe do a combo, and call it something like "Truncate expansion" (?) haha

**Comment by mcoker** [comment]
@mcarrano @mmenestr an issue with the expandable section toggle now is that it has its own button and doesn't use our button component. If we want to support an inline link there, I'd like to look at enhancing that so a regular button component can be used.

Also a side note - should the caret be our secondary color by default, and the primary color on hover/focus/active/expanded?

**Review by srambach — APPROVED** [review]
LGTM 👍

**Comment by mcoker** [comment]
per @mcarrano, updated the truncate toggle to remove the icon and extra spacing.

The toggle text is still darker when the text is expanded - is that good or should it stay the same between truncated/expanded? @mmenestr @mcarrano 

Screen Shot 2022-08-01 at 6 35 17 PM

Default variation for comparison

Screen Shot 2022-08-01 at 6 35 30 PM

**Review by mcarrano — APPROVED** [review]
This looks good @mcoker . Thanks for making these updates. I am fine with the "Show less" text being darker for consistency with the other variants.

**Review by mmenestr — APPROVED** [review]

**Pull request merged**
