### PR TITLE
fix(wizard): added cancel button element to increase cancel spacer

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/1894

Once the action list component is promoted, we can use that here for more flexibility.

### CODE REVIEW

**Comment by matthewcarleton** [comment]
Thanks for doing this @mcoker I'm leaning towards 16px instead of 32px (I think that's what @mceledonia suggested too). 
Screen Shot 2020-12-15 at 9 23 02 AM

**Comment by mceledonia** [comment]
I'm thinking 24px or 16px should work well! I do like it being spaced a little further out than the primary and secondary action.

**Comment by mattnolting** [comment]
> Thanks for doing this @mcoker I'm leaning towards 16px instead of 32px (I think that's what @mceledonia suggested too). Seeing 48px in the browser now feels a bit extreme ( I know I suggested it so my bad :) )

@mceledonia @matthewcarleton @mcoker WDYT about zeroing the left/right padding on the `cancel` button to avoid inadvertent clicks as @matthewcarleton [noted here](https://github.com/patternfly/patternfly/issues/1894#issue-452591166), with a 16px margin-left? 

Looks like this:

Screen Shot 2020-12-15 at 9 56 11 AM

Screen Shot 2020-12-15 at 9 56 18 AM

**Comment by mcoker** [comment]
@matthewcarleton @mceledonia when we created the action list, the docs said the space should be 48px in the wizard, too - https://docs.google.com/presentation/d/1Kh8wGM27X5shhSyVpZbgjV3uidpOmlz-CLYWHhxEMEI/edit#slide=id.g6c2040c51b_2_17

Since the action list has a 48px for groups, I was expecting that to be used here once the component is promoted from beta.

Just want to confirm we want to deviate from the 48px spacing, and assuming so, whether we want to push this change back to the action list. I assume we'll also want to have cancel spacing other places, like the form component, so it would be good if the action list supports a unique cancel spacing so we can use that component instead, and also extend the ability to use groups in wizards, forms, etc.

**Comment by mcarrano** [comment]
I agree that we should be consistent with what we defined for the Action list so we can later use that component. If we really want to revisit this, let's make the update there also, but personally I'm OK with the 48px spacing.

**Comment by matthewcarleton** [comment]
ah ok - I won't rock the boat then. Happy to go with this @mcoker

**Comment by mceledonia** [comment]
Agreed, given the context of the decision I think we're alright to leave it as-is.

**Review by matthewcarleton — APPROVED** [review]
LGTM!

**Review by mcarrano — APPROVED** [review]
Looks good!

**Review by mattnolting — APPROVED** [review]
I'd like to revisit spacing later, bc it looks too big to me, but the update is 💯

**Pull request merged**
