### PR TITLE
fix(context-selector): left aligned footer

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3971

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
This looks great @mcoker . Will this require any React update or is this strictly a CSS level change?

**Comment by mcoker** [comment]
@mcarrano the alignment comes for free, but the action in the react workspace example is a link button and that should be updated to be an inline link - https://patternfly-react.surge.sh/components/context-selector#with-footer

**Review by mattnolting — APPROVED** [review]
Perfect!

**Pull request merged**
