### PR TITLE
fix(vars): added quotes around sass vars to retain quotes when compiled

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3512

### CODE REVIEW

**Review by sosguthorpe — APPROVED** [review]
Works perfectly for me locally, and allows me to remove my workaround. So big thumbs up from me!

**Review by redallen — APPROVED** [review]

**Review by redallen — CHANGES_REQUESTED** [review]
Ah sorry, there's a build error: `Error: Can't resolve '"./assets/pficon"/pficon.eot' in '/home/circleci/project/dist`

**Comment by sosguthorpe** [comment]
> Ah sorry, there's a build error: `Error: Can't resolve '"./assets/pficon"/pficon.eot' in '/home/circleci/project/dist`

FWIW I've just seen similar in browser errors and was just coming to comment. Apologies for not being as thorough as I should have been.
In my workaround I haven't changed the SCSS variable declarations, but instead just the CSS variable output here:
https://github.com/patternfly/patternfly/blob/3c4ee90115901b7e5bd61834ea77f80f29416909/src/patternfly/base/_variables.scss#L161
with similar to this, as it's only the CSS variable that are invalid. 
```
  // Fontpath
  --pf-global--font-path: "#{$pf-global--font-path}";

  // FontIconPath
  --pf-global--fonticon-path: "#{$pf-global--fonticon-path}";
```

I can raise a PR, instead of commenting here, if people would prefer?

**Comment by redallen** [comment]
@sosguthorpe You're always welcome to open a PR!

**Comment by mcoker** [comment]
@sosguthorpe @redallen thanks for catching that! Pushed an update, do you mind re-reviewing?

**Review by redallen — APPROVED** [review]

**Review by mattnolting — APPROVED** [review]
LGTM 👍

**Review by sosguthorpe — APPROVED** [review]

**Pull request merged**
