### PR TITLE
fix(radio,checkbox,form): Correct label alignment

### LINKED ISSUE #3868: form: vertical alignment issues
1. There are issues with the checkboxes and radio buttons not being properly aligned with their textual labels. This is slightly different per browser.
2. Labels for form elements are down too low (or are elements too high?)

Included are screenshots that show these issues, from Firefox:

In Cockpit:

Screenshot from 2021-02-17 13-00-25

Screenshot from 2021-02-17 13-00-16

On the PatternFly website:

Screenshot from 2021-02-17 13-08-19

Screenshot from 2021-02-17 13-07-27

Expect results would be:
- Checkbox and radio buttons should look vertically centered to the first line of text
- Labels and form elements should be aligned to baseline

### PR DESCRIPTION
**Pull request by srambach**
This does some math to calculate the distance from the top of the element to the baseline so that the horizontal form labels and also the checkbox/radio button labels can be properly aligned vertically.
Sadly, in Firebox, aligning the label/input to "baseline" doesn't give the desired behavior on multi-line inputs.

Old and new alignment here:
image

Fixes #3868

### CODE REVIEW

**Review by garrett — APPROVED** [review]
@srambach: This is **_wonderful!_**

I took a few screenshots on Fedora Linux 35 (beta):

## Firefox

Screenshot from 2021-09-16 16-21-44


## GNOME Web (WebKit, basically Linux's Safari)

Screenshot from 2021-09-16 16-23-21

 
## Chromium

Screenshot from 2021-09-16 16-24-33

---

It looks _perfect_ in all the browsers except for the "Name" field in Chromium. It's fine in Information and looks good in the options as well, so I think there's a half pixel rounding error somewhere, where it rounds inconsistently in some cases.

It's definitely an improvement and fixes it everywhere (except for that pixel rounding in Chrome for whatever reason... I'm guessing a minor browser or font rendering bug), so I wholeheartedly approve!

**Comment by garrett** [comment]
I have a Windows VM I'm launching right now to try to see what happens in browsers in Windows versus Linux, just as a third point of comparison (assuming you're using a Mac, since you have Safari examples).

**Comment by srambach** [comment]
> I have a Windows VM I'm launching right now to try to see what happens in browsers in Windows versus Linux, just as a third point of comparison (assuming you're using a Mac, since you have Safari examples).

Yes, I'm on a mac. Thank you for the additional testing!

**Comment by garrett** [comment]
## Windows Firefox

Screenshot from 2021-09-16 16-59-19

Oddly, it's all off a pixel... some up, some down.

## Windows Edge (Chromium)

Screenshot from 2021-09-16 16-59-31

Chrome has the same off-by-one on the first input ("Name"), similar to Linux.

---

It seems Windows renders a little different from Linux and Mac. Still, this is already a lot better than what we currently have!

**Comment by srambach** [comment]
Here's MS Edge Canary on my Mac.
image

**Comment by garrett** [comment]
Oh, interesting! It seems like Chromium has fixed the rendering issue then? I'll try newer versions here on Linux too.

Also, the Edge I was testing is Chromium edge, just to be clear (not the old EdgeHTML Edge).

**Comment by garrett** [comment]
## Windows Chrome Canary
Screenshot from 2021-09-16 17-50-13

It looks like someone fixed the rounding error in somewhere between Chromium stable (and Edge Beta on Linux) and Chromium Canary builds!

## Windows Firefox Nightly

Screenshot from 2021-09-16 17-51-51

Firefox on Windows is just weird for some reason.

---

OK, assuming the rounding error we see fixed in Canary builds of Chromium also show up in Linux (which renders otherwise the same as the other platforms it seems), that would mean that you've achieved perfect placement of the labels in all browsers except Firefox on Windows specifically, right?

I'd suggest we go forward with this and just ignore Firefox on Windows. It's only off by a pixel, which is still better than being off by two. And everything else (including Firefox on other platforms) can benefit from the better calculation!

Thanks again! :+1:  :tada:

**Review by mcoker — APPROVED** [review]
LGTM! 🤯

**Pull request merged**
