### PR TITLE
chore(card): moved card view demo to demos, renamed card demo files

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3958

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks great. Thanks @mcoker !

**Review by mattnolting — APPROVED** [review]
LPTM! 🥳

**Comment by mattnolting** [comment]
Oop, looks like there's a conflict

**Comment by mcoker** [comment]
@mattnolting updated. The text for the empty state card in the [card view demo](https://patternfly-pr-3989.surge.sh/demos/card-view/html-demos/card-view/) just needs to match the update from this PR - https://github.com/patternfly/patternfly/pull/4001/files

**Pull request merged**
