### PR TITLE
fix(global-vars): updated active-color--300 and 400

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3618

### CODE REVIEW

**Review by gdoyle1 — APPROVED** [review]
LGTM

**Comment by mcarrano** [comment]
What should I be looking for here @mcoker ?

**Comment by mcoker** [comment]
@mcarrano 

This PR changes:
* Old - `$pf-global--active-color--300: $pf-color-blue-200 (#73bcf7)`
* New - `$pf-global--active-color--300: $pf-color-blue-300 (#2b9af3)`

* Old - `$pf-global--active-color--400: $pf-color-blue-300; (#2b9af3)`
* New - `$pf-global--active-color--400: $pf-color-blue-200; (#73bcf7)`

Places we use `$pf-global--active-color--300`:
* Data-list - the left row border when a row is both expanded and selected (in a list with selectable rows)
* `$pf-global--link--Color--light` - this is the link color anywhere we have defined a dark theme. We use dark theme in:
  * Login header and footer
  * Page masthead
  * About modal box
  * Dark banners (anywhere the text color is white)
  * Wizard header


Places we use `$pf-global--active-color--300`:
* `$pf-global--link--Color--light--hover` - the link hover color in a dark theme
* Navigation - used for the blue accent color for active/current nav items and horizontal nav hover color.

**Review by mcarrano — COMMENTED** [review]
Thanks for the clarification @mcoker . Looks fine to me but I will defer to @mceledonia

**Review by mceledonia — APPROVED** [review]

**Review by ajacobs21e — APPROVED** [review]

**Review by christiemolloy — APPROVED** [review]
LGTM

**Pull request merged**
