### PR TITLE
feat(integration): add snapshot tests for all components

### LINKED ISSUE #1123: Regression testing - investigation
Investigate and prototype a regression testing solution that will provide build/pr time feedback on breaking changes.  

Visual regression has been deemed too fragile to qualify for this - one idea the team has is to use a snapshot of the DOM w/applied styles (see this repo:  https://azaslavsky.github.io/domJSON/).  We could store these representations and compare at build time to make sure we haven't broken anything.

### PR DESCRIPTION
**Pull request by redallen**
Closes #1123

This PR uses [webdriverio](https://webdriver.io/) as a test framework that wraps Mocha and Selenium. A service for it called [wdio-image-comparison-service](https://github.com/wswebcreation/wdio-image-comparison-service) uses [Resemble.js](https://github.com/rsmbl/Resemble.js) to compare snapshots, and a reporter called [Allure](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-allure-reporter) displays test results.

Tests are run in Chrome in parallel in up to 10 browsers at 1024x768px by leveraging [BrowserStack](https://www.browserstack.com/automate/webdriverio).

We could potentially check more breakpoints and browsers at the cost of more time or using multiple Browserstack accounts. Breakpoints of interest are 576px, 768px, 992px, 1200px, and 1450px.

Snapshots have been committed using the Git plugin [Git LFS](https://git-lfs.github.com/). By doing this, they aren't stored in the repo's `.git` directory. However, if someone _commits_ images to this directory without the plugin installed, they will be in the repo's `.git` directory, and it's annoying (but possible!) [to add them back to Git LFS again.](https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs)

### CODE REVIEW

**Comment by redallen** [comment]
This has too much overhead or needs a dedicated machine to reasonably accommodate development. Closing

**Comment by castastrophe** [comment]
@redallen @starryeyez024 (Kendall) and I have some experience in optimizing visual regression testing in the pattern library that is used for redhat.com and would be happy to share some cost-cutting, space-saving approaches.  Our system can definitely use some work, especially as regards browser testing, but at least in the area of reducing snapshots, we have been pretty successful.  Let me know if you want to sync up.

**Comment by redallen** [comment]
cc: @mcoker @dgutride Are you interested?

**Comment by dgutride** [comment]
@castastrophe  - thanks for the comment - this PR is closed currently and if you have suggestions or something you'd like for us to look at - could you add some details over here:  https://github.com/patternfly/patternfly/issues/2673 ?

**Comment by castastrophe** [comment]
@dgutride 👍

**Pull request closed without merging**
