### PR TITLE
Reorganize pages in workspace

### LINKED ISSUE #5414: Workspace - move pages per v5 website IA
Follow up on: https://github.com/patternfly/patternfly-org/pull/3416

Want to move/rename pages that are used to populate the PF website. Affected pages include:

Release notes
Demos:
* Card view
* Dashboard
* Password generator
* Password strength
* Primary-detail

Utilities (rename to Utility classes)

Group menu and form components using tertiary nav. See https://github.com/patternfly/patternfly-org/issues/3425 and https://github.com/patternfly/patternfly-org/issues/3426

### PR DESCRIPTION
**Pull request by mcarrano**
Make the following changes to workspace organization:
- Rename primary sections
- Move release notes to 'Get started'
- Change 'Demos' to 'Patterns' and move Password generator and Password strength to 'Components'
- Change 'Utilities' to 'Utility classes'
- Groups Dropdown, Menu, Menu toggle, and Select into a new category named "Menu"
- Groups Checkbox, Form, Form control, and Radio into a new category named "Forms"
- Groups Text file upload and Multiple file upload into a new category named "File upload"

Closes #5414

### CODE REVIEW

**Comment by mcarrano** [comment]
@evwilkin @mcoker I've put this PR up to move files in the core workspace as we discussed on Friday. Looks like everything previews as intended except that I lost the screenshots for the full page demos in what's now labeled the "Patterns" section. Is there something else I need to change to account for the change in naming from "Demos" to "Patterns?"

**Comment by mcarrano** [comment]
@evwilkin @mcoker @nicolethoen I've made additional changes to group certain items inside the Components section using tertiary nav as we discussed. This should now be ready for final review. If we are good with these changes, I will make the equivalent updates in React repo.

**Comment by nicolethoen** [comment]
might it also be worth moving the (soon to be deprecated) application launcher and context selector to the menus tertiary section?

**Comment by mcarrano** [comment]
Yes, I agree that makes sense. Will update.

**Comment by mcarrano** [comment]
Have added Application launcher, Context selector, and Options menu to Menus. PLease re-review.

**Review by nicolethoen — APPROVED** [review]

**Comment by mcarrano** [comment]
I made one additional change to group all components and demos related to Date and Time by creating a new components/date-and-time category. For core there is only Date picker, but React will include more things (Time picker and Date & Time and Date Range demos). Please re-review.

**Review by evwilkin — APPROVED** [review]
LGTM

**Pull request merged**
