### PR TITLE
chore(docs-framework): consume alphas to build v6 workspace

### PR DESCRIPTION
**Pull request by nicolethoen**

### CODE REVIEW

**Review by mcoker — APPROVED** [review]
🤗

**Review by evwilkin — APPROVED** [review]
LGTM - thanks for the work getting this passing!

**Review by mcoker — CHANGES_REQUESTED** [review]
Sorry, I merged a [docs framework dependency](https://github.com/patternfly/patternfly/pull/6230) update from main into v6 and caused a conflict in this PR - would you mind updating?

**Review by mcoker — APPROVED** [review]
🥳

**Pull request merged**
