### PR TITLE
fix(lists): adjust list and content list indentation

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/6800

Backstop report - [backstop-lists-6.25.24.pdf](https://github.com/user-attachments/files/15981476/backstop-lists-6.25.24.pdf)

### CODE REVIEW

**Review by thatblindgeye — APPROVED** [review]

**Review by andrew-ronaldson — APPROVED** [review]
Ship to shore!

**Review by andrew-ronaldson — APPROVED** [review]
This changed my life.

**Comment by srambach** [comment]
Page 5 of the backstop report shows a slight difference in the vertical spacing when an inline list wraps - but I think it's better, just wanted to check - @andrew-ronaldson ?

We don't seem to have documentation on the `pf-v6-c-list__item`, `pf-v6-c-list__item-text`, `pf-v6-c-list__item-icon` - should we add it?

**Comment by andrew-ronaldson** [comment]
@srambach I'm good with the difference from the backstop report.

**Comment by mcoker** [comment]
@andrew-ronaldson this is the change @srambach is referring to, I added an `xs` row-gap to inline list items when they wrap.

Screenshot 2024-06-26 at 9 28 13 AM

**Pull request merged**
