### PR TITLE
Add jsx for card

### PR DESCRIPTION
**Pull request by cliffpyles**
Add jsx/html for card

Issue: https://github.com/patternfly/patternfly-next/issues/31

### CODE REVIEW

**Comment by andresgalante** [comment]
Let mw talk again with Kyle about cards vs a generic box and I'll get back to this one.

**Comment by cliffpyles** [comment]
@andresgalante Should I close this one out?

**Comment by cliffpyles** [comment]
@dgutride @andresgalante I don't think this is needed anymore. Care if I close it?

**Comment by cliffpyles** [comment]
@dgutride @andresgalante I don't think this is needed anymore. Care if I close it?

**Comment by LHinson** [comment]
@cliffpyles agreed. I'll close.

**Pull request closed without merging**
