### PR TITLE
[DO NOT MERGE] fix(workspace): update react and @patternfly packages

### PR DESCRIPTION
**Pull request by redallen**
Removes the `@patternfly/patternfly` self dependency which should allow the theme to copy from `dist/assets` instead of `node_modules/@patternfly/patternfly/dist/assets` so that @mattnolting can move the card demo images from https://github.com/patternfly/patternfly/tree/master/static/assets/images to https://github.com/patternfly/patternfly/tree/master/src/patternfly/assets/images

Towards #3970

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]

**Comment by nicolethoen** [comment]
I guess I looked at and approve the changes - I don't approve of a failing a11y test. Not sure what that's about

**Comment by redallen** [comment]
Don't merge this yet, I'm sifting through dependency hell!

**Comment by mcoker** [comment]
@redallen should we leave this open?

**Comment by redallen** [comment]
@mcoker Yeah, I still need to update `@patternfly/patternfly-a11y`.

**Comment by redallen** [comment]
This has been accomplished in other PRs.

**Pull request closed without merging**
