### PR TITLE
feat(table): added support for single row radio select

### PR DESCRIPTION
**Pull request by mcoker**
This just extends the existing checkbox structure to support radio buttons.

fixes https://github.com/patternfly/patternfly/issues/3418

### CODE REVIEW

**Review by mcarrano — APPROVED** [review]
Looks good to me @mcoker 

@mmenestr can you also take a look and confirm that this is what you expected?

**Review by mceledonia — APPROVED** [review]

**Comment by mmenestr** [comment]
Visually looks good, but I am able to press multiple radio buttons at once? Is that because it's HTML and not React?

**Comment by mcoker** [comment]
@mmenestr nice find, that was an issue with the example code. Updated it!

**Review by mmenestr — APPROVED** [review]

**Review by mattnolting — APPROVED** [review]
Looks great, VO interaction works well too 👍

**Review by christiemolloy — APPROVED** [review]
LGTM!

**Pull request merged**
