### PR TITLE
refactor(toolbar): updated search to text-input-group

### LINKED ISSUE #4949: Toolbar - update toolbar search input group to text input groups

### PR DESCRIPTION
**Pull request by mattnolting**
closes #4949

### CODE REVIEW

**Review by srambach — APPROVED** [review]
LGTM

**Comment by mcoker** [comment]
@srambach pushed a change to update the search input in the log viewer toolbar and removed an old/unused skeleton component partial that referenced search input in a toolbar. I also created a new [text-input-group--search-input.hbs](https://github.com/patternfly/patternfly/blob/3894ea9b40582cf5b71f5105982bb595eb60166c/src/patternfly/components/TextInputGroup/text-input-group--search-input.hbs) that takes param values to build out the structure for us (based on search input) and updated the text input group's search input examples to use it, which should make developing/testing easier.

**Review by mcoker — APPROVED** [review]

**Review by srambach — APPROVED** [review]
I approve if you think the file is in the right place, but seems like it should go into templates?

**Review by srambach — APPROVED** [review]
👍

**Pull request merged**
