### PR TITLE
feat(tabs): added close button and add new tab

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4757

There is currently no styling or anything associated with the "add new tab" tab - it's just a regular tab with an icon. @mcarrano @mmenestr wdyt?

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
@mcoker thanks for sharing this. I feel like the Close button is a little heavy visually. I know that's our standard icon button styling, but maybe we need something different here? I have a similar feeling about the Add (+) button. @mceledonia can you take a look at this?

**Comment by mceledonia** [comment]
@mcarrano @mcoker Yeah, I think we can drop down the icon size to small for both close and add, then keep the same padding shown above. Here's a quick mockup of how that looks:

image

**Comment by christianvogt** [comment]
IMO the padding to the left and right of the `x` button seems off as the gap on the right is smaller. But maybe that's ok?
image


I was testing the addition of the close button to several other variants and there seems to be issues.
image
image

**Comment by mceledonia** [comment]
I'm ok with them being different (left vs right padding) but the padding on the right does feel rather tight on the box variation due to the border being more visible. Any reason not to have separate right-hand padding between box and filled variations? On box I would propose bumping it up a spacer to better balance against the more visible shape of the tab.

**Comment by mcoker** [comment]
@mceledonia here is the change with extra padding on the right in the box variation

Screen Shot 2022-04-12 at 1 51 47 PM

FWIW, here's that change but applying it to the close button globally. I think this looks OK too.

Screen Shot 2022-04-12 at 1 53 36 PM

And this is the same change, but using equal left/right padding on the close button, which separates the text and close button a bit.

Screen Shot 2022-04-12 at 1 48 47 PM

wdyt?

**Comment by mceledonia** [comment]
@mcoker I actually think it looks fine on both, thanks for trying it out. These look great to me!

**Comment by mmenestr** [comment]
The only comment I have (and maybe it's just me) but visually, the text and x icon don't look like they're aligned - ie: the x icon sits a little higher than the text and it feels off to me? Idk if that's something that can be changed though. Looks like they are vertically center aligned when I use inspect which in theory is correct, but wonder what it would look like if the X was a few pixels lower, to bottom align with the text?

**Comment by mcarrano** [comment]
@mcoker I like this much better now. I think the question that @mmenestr raised is an interesting one. I hadn't noticed it until I read her comment. Is that a function of the X icon being enclosed in a button?

Also, I wondered if we could change the last example to include both the Close button and the Add button together to see what this will really look like. I can't see a case where we would support adding new tabs without the ability to remove them.

**Comment by mcarrano** [comment]
@mcoker thanks for adding the additional examples. It does highlight one problem with how this is implemented, however. Looks like the Add button is just another tab that means it gets hidden when the tabs overflow and horizontal scrolling is exposed. I'd expect the Add button to always be visible. The way Firefox handles this is a good model I think.

Screen Shot 2022-04-13 at 9 42 04 AM

Note that the Add button exists outside of the tab group following the scroll button so it is always available. Can we do something like that?

**Comment by mcoker** [comment]
@mcarrano yep we can, though I'll note that I asked about that specifically in one of the planning meetings and we decided it should just be another tab at the end of the list, contained within the scroll buttons - you would need to scroll to the end of the list to see the add tab button. Just want to mention that in case there was a specific reason for that - or maybe I miscommunicated/misunderstood our previous convo 😁

Also assuming we move it out of the list and scroll buttons (when present), should it still look like a regular tab (including the basic tab hover/focus styling) or should it have a more generic style?

**Comment by mmenestr** [comment]
That looks better @mcoker thank you!
And I kind of agree with Matt that it would maybe be better to move it outside - I don't remember the tab conversation so I can't say why we didn't say that before but, one thing I like about moving it outside, apart from it not getting lost, is that there's also a clearer visual distinction between the end of a tab and the start of the + tab. Right now there's no line or anything between them which feels weird to me.

**Comment by christianvogt** [comment]
I highlighted the use of the tab as the add button in the original defect https://github.com/patternfly/patternfly/issues/4757

If we can solve the issue of it being hidden while still being present adjacent to the last opened tab (instead of right justified), that would be my preference.

**Comment by mcarrano** [comment]
> @mcarrano yep we can, though I'll note that I asked about that specifically in one of the planning meetings and we decided it should just be another tab at the end of the list, contained within the scroll buttons

Yeah, sorry about that @mcoker . I may have said that without realizing what the implications of that would be.

> Also assuming we move it out of the list and scroll buttons (when present), should it still look like a regular tab (including the basic tab hover/focus styling) or should it have a more generic style?

I think the later, because it would be wrong, IMO, for this to be styled as a tab, but not behave like the other tabs. Do you agree @mceledonia @mmenestr ?

> If we can solve the issue of it being hidden while still being present adjacent to the last opened tab (instead of right justified), that would be my preference.

I agree

**Review by mceledonia — APPROVED** [review]
Latest looks good!

**Comment by mcarrano** [comment]
@mcoker the screen grab above looks great. For some reason, the preview still feels like it has more padding for the scroll button, or is that my imagination?

Screen Shot 2022-04-13 at 4 29 15 PM

**Review by mcarrano — APPROVED** [review]
Everything looks good. Thanks @mcoker !

**Review by mattnolting — APPROVED** [review]
Nice work! LPTM

**Pull request merged**
