### PR TITLE
feat(empty-state): added xs variation

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3513

### CODE REVIEW

**Review by mcarrano — CHANGES_REQUESTED** [review]
The extra small empty space should not include an icon. See the designs here https://marvelapp.com/prototype/7c5cdhd/screen/72928590. Please reach out to @mmenestr if you have questions.

**Comment by mcoker** [comment]
@mcarrano ah ok, I didn't see that as a requirement. Technically you can still use one, but I removed it from the example. Would we want to decrease the icon size if a user did include an icon?

**Comment by mcarrano** [comment]
I think so. @mmenestr ?

**Comment by mmenestr** [comment]
I agree that we should still give people the option to add an icon if they wanted to, although in most cases it may not fit. 
I just did a test of 24px vs 54px icon, and I think I would keep the icon at 54px since there is no in between size (based on PF icon sizing), and the 24px looks too small IMO.  One other thing is the spacing between the body and the buttons should be 16px not 32px! Otherwise, looks great!

image

**Comment by mcoker** [comment]
Thanks @mmenestr forgot to update that spacing! Here is what it looks like with an icon and primary button, if someone were to put those in. 16px between all sections, except I'm retaining the 8px spacer between the primary button and secondary list, which is used in the other variations.

**Review by mattnolting — APPROVED** [review]
LGTM

**Review by mmenestr — APPROVED** [review]

**Review by christiemolloy — APPROVED** [review]
LGTM!!

**Review by mcarrano — APPROVED** [review]
Looks great. Thanks @christiemolloy !

**Pull request merged**
