### PR TITLE
fix(inputgroup): fix double line in invalid

### LINKED ISSUE #2732: Input group - form control invalid state has double border
This block is causing a double border between the invalid form control and the element that follows it:

https://github.com/patternfly/patternfly-next/blob/9d75002b14731c7d13d2ff531f0368981228770b/src/patternfly/components/InputGroup/input-group.scss#L41-L47

Screen Shot 2020-02-20 at 11 20 28 AM

### PR DESCRIPTION
**Pull request by christiemolloy**
closes #2732 

@mcoker can this be positioned as a bug so that I can remove the block and variable ?

### CODE REVIEW

**Comment by mcoker** [comment]
> can this be positioned as a bug so that I can remove the block and variable ?

Unless there is a benefit, I would just leave it to be on the safe side.

**Review by mcoker — APPROVED** [review]
Perfect!

**Review by mattnolting — APPROVED** [review]
LPTM!

**Pull request merged**
