### PR TITLE
chore(drawer): added demos with jumplinks

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4512

drawer collapsed - https://patternfly-pr-4608.surge.sh/components/drawer/html-demos/drawer-with-jump-links
drawer expanded - https://patternfly-pr-4608.surge.sh/components/drawer/html-demos/expanded-drawer-with-jump-links

### CODE REVIEW

**Review by mattnolting — COMMENTED** [review]
Implementation is 👍 . I see what you're going for in the example structure, it's cool. However, in this example the code is repeated and would need to be repeated in further examples that could share this content. I think it would more straightforward to put the custom code in it's own partial and `*inline` it like you have here or just wrap with `drawer-demo-default` and set the custom flag on that template.

**Comment by srambach** [comment]
The jumplinks aren't sticky here. I think the goal was to show how jumplinks can work while also having a drawer on the page. Does this need to be a React demo instead?

**Comment by mcarrano** [comment]
What's the status of this one @mcoker ? Looks like it's been sitting idle for a while.

**Comment by mcoker** [comment]
@mcarrano I'm going to try and address this milestone.

**Comment by wise-king-sullyman** [comment]
Will this PR be able to make it in this milestone? It is a blocker for https://github.com/patternfly/patternfly-react/issues/6582 which I'm slated to work on next milestone.

**Comment by mcoker** [comment]
@wise-king-sullyman I don't think so, it's lower priority so it's likely going to move into the next milestone.

**Review by mcarrano — COMMENTED** [review]
Looks OK to me. But I will pass as I'm not exactly sure what we were intending to demo here.

**Comment by srambach** [comment]
Section ids are `-first`, `-second` etc - is that intended or should there be a prefix?

Since the jumplinks highlighting (showing the current section) does not work without JS, there should be text along with the demo explaining this - otherwise it just looks like our demo is broken.

`pf-c-drawer__content` is the scrollable container here that needs to be used as the scrollable selector by the scrollspy. It would be better if there were a unique id on this element because if there is more than one `pf-c-drawer__content` for some reason, the scrollspy will not work properly.

Finally, I would like to see a link to this demo from the jumplinks demo page. I don't see a need to duplicate it, but it's quite likely that someone trying to make this work would be looking at the jumplinks component, not at the drawer component.

**Comment by mcoker** [comment]
@srambach updated!

**Review by srambach — APPROVED** [review]
🎉 Great!

**Pull request merged**
