### PR TITLE
fix(toolbar): changed expand content zindex to sm to match other menus

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3983

### CODE REVIEW

**Review by mattnolting — APPROVED** [review]
LPTM! 🌮

**Comment by jgiardino** [comment]
Thanks for fixing this so fast! I'm not really sure how to test this without being able to show the filter menu on top of a data view. I couldn't find any html demos with this exact display state. But I have faith that it works as expected.

**Comment by mcoker** [comment]
@jgiardino you can inspect the toolbar component in the demo you linked to in the [original issue](https://github.com/patternfly/patternfly/issues/3983), and find the declaration `--pf-c-toolbar__expandable-content--ZIndex: var(--pf-global--ZIndex--xs);` in the var list, and change the value from `--pf-global--ZIndex--xs` to `--pf-global--ZIndex--sm`. Then do the hover test you described to reproduce the problem.

Or you can also assign `--pf-c-toolbar__expandable-content--ZIndex: var(--pf-global--ZIndex--sm);` as an inline var on the `.pf-c-toolbar` element.

**Pull request merged**
