### PR TITLE
feat(icon): added critical-risk pficon

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/4747

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
@mcoker other than seeing that you did add this to the files attached in this PR, is there anything else I can or should do to review this. So far, looks good as far as I can tell.

**Comment by mcoker** [comment]
@mcarrano just verify it looks OK on the icon page - https://patternfly-pr-4758.surge.sh/icons

**Comment by mcarrano** [comment]
@mcoker OK. Forgot about that page. Yes, I see it and it looks good. But I do have another question- In your comment here: https://github.com/patternfly/patternfly/issues/4747#issuecomment-1079276419, you noted that the other three icons were already present in the icon set. If that's the case, how come they don't show up on the Icons page referenced above?

**Comment by mcoker** [comment]
@mcarrano the icons on that page are from the "pficon" icon font - the other icons are part of Font Awesome solid. I could probably update that page to include our bundled FAS icons, too, if you think that would be helpful.

**Comment by mcarrano** [comment]
@mcoker that's probably not necessary since it's not a page that appears publicly on the website. I will approve.

**Review by mcarrano — APPROVED** [review]
Thanks, @mcoker !

**Comment by doruskova** [comment]
@mcoker Thank you a lot!

**Pull request merged**
