### PR TITLE
feat(icon): added data-processor icon

### PR DESCRIPTION
**Pull request by mcoker**
**preview link: https://patternfly-pr-5284.surge.sh/icons**

fixes https://github.com/patternfly/patternfly/issues/5263

### CODE REVIEW

**Review by mcarrano — COMMENTED** [review]
Looks good to me. @yichen1yu can you also verify? 

@mcoker My only question is about naming. I was calling this `data-processor` and you have it here as just `processor` See Org issue: https://github.com/patternfly/patternfly-org/issues/3326. Which should it be? @yichen1yu do you have a preference? My only caution with using the name "processor" is that people could confuse this with the hardware processor as in a CPU. Thoughts?

**Comment by mcoker** [comment]
@mcarrano thanks for the org issue link! Re-read the design issue and looks like this is complimentary to data-sink and data-source, so I went ahead and updated the icon name to data-processor.

**Comment by yichen1yu** [comment]
@mcarrano @mcoker Yes it should be data-processor as Michael pointed out we already have data-sink and data-source. I guess we just follow that pattern

**Comment by yichen1yu** [comment]
@mcoker I tried this link https://patternfly-pr-5284.surge.sh/icons and found there shows no icon on the "processor" and didn't find a "data-processor" in the column. Would mind pointing me where to see the preview? Thanks!!

**Comment by yichen1yu** [comment]
@mcoker Thank you. Looks good!

**Review by mcarrano — APPROVED** [review]
LGTM. Thanks @mcoker !

**Pull request merged**
