### PR TITLE
fix(switch): adjust space between switch and label

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/3880

Looks like this was a bug introduced in https://github.com/patternfly/patternfly/pull/3749/

### CODE REVIEW

**Review by evwilkin — APPROVED** [review]
LGTM!

**Review by mcarrano — APPROVED** [review]
Definitely looks better! What do you think @mceledonia ?

**Review by mattnolting — APPROVED** [review]
LGTM 👍

**Pull request merged**
